#!/usr/bin/env node
// Source of truth: codex-pair-debounce-worker.mts. The sibling .mjs is generated by `yarn workspace @ask-llm/plugin build:hooks`; never edit it.

// Workers defer edits to the forced-sync hook, which owns the per-file lock; pending verdicts surface on a later hook.

import { type SpawnSyncReturns, spawnSync } from "node:child_process";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  clearReviewing,
  decideReview,
  markReviewed,
  markReviewing,
  readEditRecord,
  writePending,
} from "./lib/debounce-state.mts";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const HOOK_PATH = join(SCRIPT_DIR, "codex-pair-watch.mjs");

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

// Read the last parseable hook output line; earlier stdout may not be JSON.
function extractSystemMessage(stdout: string | null | undefined): string | null {
  if (!stdout) return null;
  const lines = stdout.split("\n").filter((l: string) => l.trim().length > 0);
  for (let i = lines.length - 1; i >= 0; i--) {
    try {
      const obj = JSON.parse(lines[i]);
      if (typeof obj.systemMessage === "string") return obj.systemMessage;
    } catch {
      // not JSON — skip
    }
  }
  return null;
}

async function main() {
  const markerDir = process.env.CP_MARKER_DIR;
  const file = process.env.CP_FILE;
  const tool = process.env.CP_TOOL || "Edit";
  const myGeneration = Number(process.env.CP_GENERATION);
  const settleMs = Number(process.env.CP_SETTLE_MS);
  const rawMaxMs = Number(process.env.CP_MAX_MS);
  // NaN would disable the anti-starvation cap because comparisons always fail.
  const maxMs = Number.isFinite(rawMaxMs) && rawMaxMs > 0 ? rawMaxMs : 60_000;
  if (!markerDir || !file || !Number.isFinite(myGeneration)) process.exit(0);

  await sleep(Number.isFinite(settleMs) ? settleMs : 15_000);

  const record = readEditRecord(markerDir, file);
  const decision = decideReview({ record, myGeneration, now: Date.now(), maxMs });
  if (!decision.review) process.exit(0);

  // Mark reviewing before consuming the debounce record so the Stop-gate always sees in-flight work.
  markReviewing(markerDir, file);
  // The forced-sync hook owns the concurrency lock, not this worker.
  markReviewed(markerDir, file, myGeneration);

  const payload = JSON.stringify({
    hook_event_name: "PostToolUse",
    tool_name: tool,
    tool_input: { file_path: file },
    session_id: process.env.CP_SESSION_ID || "",
  });
  const codexTimeout = Number(process.env.ASK_CODEX_TIMEOUT_MS ?? 800_000);
  let res: SpawnSyncReturns<string> | undefined;
  try {
    res = spawnSync(process.execPath, [HOOK_PATH], {
      input: payload,
      cwd: markerDir,
      encoding: "utf-8",
      env: { ...process.env, CODEX_PAIR_FORCE_SYNC: "1" },
      timeout: codexTimeout + 60_000,
    });
  } finally {
    clearReviewing(markerDir, file);
  }
  const message = extractSystemMessage(res?.stdout);
  if (message) writePending(markerDir, file, message);
  process.exit(0);
}

main().catch(() => process.exit(0));
