#!/usr/bin/env node
// Source of truth: codex-pair-watch.mts. The sibling .mjs is generated by `yarn workspace @ask-llm/plugin build:hooks`; never edit it.

// Marketplace installs have no workspace dependencies; the hook self-gates on a project marker.

import { spawn } from "node:child_process";
import { readFileSync } from "node:fs";
import { access, readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  type BrokerError,
  initializeBroker,
  isBrokerDescriptorEligible,
  isBrokerEnabled,
  readBrokerState,
  submitReview,
} from "./lib/broker.mts";
import {
  bumpEditRecord,
  DEFAULT_DEBOUNCE_MAX_MS,
  DEFAULT_DEBOUNCE_MS,
  drainPending,
  joinPendingForSurface,
  markReviewed,
  sweepStaleDebounce,
} from "./lib/debounce-state.mjs";
import { type Frontmatter, parseFrontmatter } from "./lib/frontmatter.mts";
import type { HookInput } from "./lib/hook-input.mjs";
import {
  buildVerdictMessage,
  DEFAULT_SURFACE_THRESHOLD,
  formatDuration,
  parseConcerns,
  parseResetHint,
  VALID_THRESHOLDS,
  VERDICT_PREFIXES,
} from "./lib/parser.mjs";
import { IS_WINDOWS, terminateProcessTree } from "./lib/process.mjs";
import { buildReviewPrompt } from "./lib/prompt.mjs";
import { registerMarker } from "./lib/session-registry.mjs";
import {
  AUTOPAUSE_FAILURE_THRESHOLD,
  appendLog,
  CONTEXT_FILENAME,
  clearAutoPause,
  clearReviewFailures,
  computeCacheKey,
  contextPath,
  getBlockingFromShard,
  getCachedConcerns,
  hashConcernBody,
  INFLIGHT_TTL_MIN_MS,
  ignorePath,
  includePath,
  logPath,
  PAIR_ROOT_DIR,
  readPauseInfo,
  readPluginVersion,
  recordReviewFailure,
  releaseInflightLock,
  resolveAutoResume,
  setCachedConcerns,
  tryAcquireInflightLock,
  updateRepetitions,
  writeAutoPause,
} from "./lib/state.mjs";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const DEFAULTS_PATH = join(SCRIPT_DIR, "..", "codex-pair-defaults.json");

// Use shared model defaults; malformed or missing JSON falls through to environment and inline defaults.
let CODEX_PAIR_DEFAULTS = { model: "gpt-6-sol", fallbackModel: "gpt-5.6-terra" };
try {
  CODEX_PAIR_DEFAULTS = JSON.parse(readFileSync(DEFAULTS_PATH, "utf8"));
} catch {
  // intentional fallback to inline defaults
}

const MARKER_FILE = join(PAIR_ROOT_DIR, CONTEXT_FILENAME);
const WATCHED_TOOLS = new Set(["Edit", "Write", "MultiEdit"]);
const DEFAULT_MODEL = process.env.ASK_CODEX_MODEL ?? CODEX_PAIR_DEFAULTS.model;
const FALLBACK_MODEL = process.env.ASK_CODEX_FALLBACK_MODEL ?? CODEX_PAIR_DEFAULTS.fallbackModel;
const CODEX_REASONING_EFFORTS = new Set(["low", "medium", "high", "xhigh", "max", "ultra"]);
const configuredReasoningEffort = process.env.ASK_CODEX_REASONING_EFFORT;
const DEFAULT_REASONING_EFFORT =
  configuredReasoningEffort && CODEX_REASONING_EFFORTS.has(configuredReasoningEffort)
    ? configuredReasoningEffort
    : "medium";
const DEFAULT_TIMEOUT_MS = Number(process.env.ASK_CODEX_TIMEOUT_MS ?? 800_000);
const MAX_FILE_BYTES = Number(process.env.CODEX_PAIR_MAX_FILE_BYTES ?? 20_000);
const DEBOUNCE_MS = Number(process.env.ASK_CODEX_DEBOUNCE_MS ?? DEFAULT_DEBOUNCE_MS);
const DEBOUNCE_MAX_MS = Number(process.env.ASK_CODEX_DEBOUNCE_MAX_MS ?? DEFAULT_DEBOUNCE_MAX_MS);
const QUOTA_SIGNALS = [
  "rate_limit_exceeded",
  "quota_exceeded",
  "429",
  "insufficient_quota",
  // ChatGPT-plan phrasings (#176) — API-style signals above never match these.
  "usage limit",
  "rate limit",
];

// An unavailable fallback model after primary quota failure means no usable model remains.
const MODEL_UNAVAILABLE_SIGNALS = ["is not supported when using codex with a chatgpt"];

// Retry transient provider failures once; quota, local timeout, and parse failures use separate paths.
const TRANSIENT_SIGNALS = [
  /ECONNRESET/,
  /ECONNREFUSED/,
  /ETIMEDOUT/,
  /EAI_AGAIN/,
  /UND_ERR/,
  /\b502\b/,
  /\b503\b/,
  /\b504\b/,
];

// Anchor unhandled-error logs to the edited file’s repository, falling back to cwd before payload parsing.
let markerAnchor: string | null = null;

type ReviewError = BrokerError & { quotaExhausted?: boolean };

interface GlobRule {
  negate: boolean;
  pattern: string;
  raw: string;
}

const SKIP_PATTERNS = [
  // Path patterns — leading/trailing slash guards against substring matches
  "/node_modules/",
  "/dist/",
  "/.git/",
  // Lockfiles by exact filename
  "yarn.lock",
  "package-lock.json",
  "pnpm-lock.yaml",
  "Cargo.lock",
  "Gemfile.lock",
  "composer.lock",
  "poetry.lock",
  "go.sum",
  // Images
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".svg",
  ".ico",
  // Fonts
  ".woff",
  ".woff2",
  ".ttf",
  ".otf",
  ".eot",
  // Documents + archives
  ".pdf",
  ".zip",
  ".tar",
  ".gz",
  // Snapshots, sourcemaps, minified assets
  ".snap",
  ".map",
  ".min.js",
  ".min.css",
  // Generic .lock catch-all (matches anything ending in .lock)
  ".lock",
];

async function readStdin(): Promise<string> {
  return new Promise((resolveRead) => {
    let data = "";
    process.stdin.on("data", (chunk) => {
      data += chunk.toString();
    });
    process.stdin.on("end", () => resolveRead(data));
    process.stdin.on("error", () => resolveRead(""));
  });
}

// Emit one JSON object per hook run; fold auto-resume notices into the next emission.
let noticePrefix: string | null = null;

// Send notices to both the transcript and model context, then await stdout flush before exit.
function emitSystemMessage(text: string): Promise<void> {
  let full = text;
  if (noticePrefix) {
    full = text ? `${noticePrefix}\n\n${text}` : noticePrefix;
    noticePrefix = null;
  }
  return new Promise<void>((resolveWrite) => {
    const payload = JSON.stringify({
      continue: true,
      systemMessage: full,
      hookSpecificOutput: { hookEventName: "PostToolUse", additionalContext: full },
    });
    process.stdout.write(`${payload}\n`, () => resolveWrite());
  });
}

// Silent exits may flush a queued notice without emitting an empty object.
function flushNoticeOnly() {
  if (!noticePrefix) return Promise.resolve();
  return emitSystemMessage("");
}

// formatDuration + buildVerdictMessage live in ./lib/parser.mjs.

// Bound git diff execution so an unavailable or hung git does not block review.
function runGitDiff({
  filePath,
  contextLines,
  cwd,
  timeoutMs,
}: {
  filePath: string;
  contextLines: number;
  cwd: string;
  timeoutMs: number;
}): Promise<string | null> {
  return new Promise((resolveDiff) => {
    let stdout = "";
    let settled = false;
    const child = spawn("git", ["diff", `-U${contextLines}`, "HEAD", "--", filePath], {
      stdio: ["ignore", "pipe", "pipe"],
      cwd,
      // Detached POSIX children let process-tree termination reach grandchildren.
      detached: !IS_WINDOWS,
    });
    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString();
    });
    child.stderr.on("data", () => {
      // discard stderr — we only care about successful diff output
    });
    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      terminateProcessTree(child, "SIGTERM");
      resolveDiff(null);
    }, timeoutMs);
    child.on("error", () => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolveDiff(null);
    });
    child.on("close", (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (code === 0 && stdout.length > 0) {
        resolveDiff(stdout);
      } else {
        resolveDiff(null);
      }
    });
  });
}

// Over-cap files use a diff, head/tail, or hard truncation; the caller marks the view partial.
async function buildAdaptiveContext({
  filePath,
  fileContent,
  markerDir,
  maxFileBytes,
}: {
  filePath: string;
  fileContent: string;
  markerDir: string;
  maxFileBytes: number;
}) {
  const diff = await runGitDiff({
    filePath,
    contextLines: 20,
    cwd: markerDir,
    timeoutMs: 5000,
  });
  const headerLines = fileContent.split("\n").slice(0, 80);
  const headerText = headerLines.join("\n");
  if (diff && Buffer.byteLength(diff, "utf8") < maxFileBytes) {
    return {
      strategy: "diff",
      content: `<file_header_first_80_lines>\n${headerText}\n</file_header_first_80_lines>\n\n<diff_against_head>\n${diff}\n</diff_against_head>`,
    };
  }
  const lines = fileContent.split("\n");
  if (lines.length <= 230) {
    const truncated = fileContent.slice(0, maxFileBytes);
    return {
      strategy: "truncated",
      content: `<file_partial_view_truncated>\n${truncated}\n[... rest of file truncated due to size cap ...]\n</file_partial_view_truncated>`,
    };
  }
  const head = lines.slice(0, 150).join("\n");
  const tail = lines.slice(-80).join("\n");
  const omitted = lines.length - 230;
  return {
    strategy: "head-tail",
    content: `<file_head_first_150_lines>\n${head}\n</file_head_first_150_lines>\n\n[... ${omitted} lines omitted ...]\n\n<file_tail_last_80_lines>\n${tail}\n</file_tail_last_80_lines>`,
  };
}

// The same ordered rule parser serves project include and ignore files.
function readGlobRulesFile(absolutePath: string): GlobRule[] {
  let content: string;
  try {
    content = readFileSync(absolutePath, "utf8");
  } catch {
    return [];
  }
  const rules = [];
  for (const rawLine of content.split("\n")) {
    const line = rawLine.replace(/\r$/, "").trim();
    if (line.length === 0 || line.startsWith("#")) continue;
    const negate = line.startsWith("!");
    const pattern = negate ? line.slice(1) : line;
    if (pattern.length === 0) continue;
    rules.push({ negate, pattern, raw: line });
  }
  return rules;
}

function readIgnoreFile(markerDir: string): GlobRule[] {
  return readGlobRulesFile(ignorePath(markerDir));
}

// A nonempty include list narrows reviews; an absent or empty list leaves all files eligible.
function readIncludeFile(markerDir: string): GlobRule[] {
  return readGlobRulesFile(includePath(markerDir));
}

// Support the common gitignore glob subset; full gitignore precedence is outside this parser.
function globToRegex(pattern: string): RegExp {
  const anchored = pattern.startsWith("/");
  const trailingSlash = pattern.endsWith("/");
  let p = anchored ? pattern.slice(1) : pattern;
  if (trailingSlash) p = p.slice(0, -1);
  let body = "";
  for (let i = 0; i < p.length; i++) {
    const c = p[i];
    if (c === "*") {
      if (p[i + 1] === "*") {
        body += ".*";
        i++;
        if (p[i + 1] === "/") i++;
      } else {
        body += "[^/]*";
      }
    } else if (c === "?") {
      body += "[^/]";
    } else if (c === "[") {
      const end = p.indexOf("]", i);
      if (end === -1) {
        body += "\\[";
      } else {
        body += p.slice(i, end + 1);
        i = end;
      }
    } else if ("().+|^$\\".includes(c)) {
      body += `\\${c}`;
    } else {
      body += c;
    }
  }
  const prefix = anchored ? "^" : "(^|.*/)";
  const suffix = "(/.*)?$";
  return new RegExp(prefix + body + suffix);
}

// The last matching rule wins, including negations.
function matchesIgnoreRule(filePath: string, markerDir: string, rules: GlobRule[]): GlobRule | null {
  if (rules.length === 0) return null;
  let rel = filePath;
  const prefix = `${markerDir}/`;
  if (filePath.startsWith(prefix)) {
    rel = filePath.slice(prefix.length);
  }
  let lastMatch: GlobRule | null = null;
  for (const rule of rules) {
    if (globToRegex(rule.pattern).test(rel)) {
      lastMatch = rule;
    }
  }
  if (lastMatch?.negate) return null;
  return lastMatch;
}

// Invalid frontmatter values fall through to environment and defaults.
function resolveConfig(frontmatter: Frontmatter | null | undefined) {
  const fm = frontmatter ?? {};
  const surfaceCandidate = typeof fm.surfaceThreshold === "string" ? fm.surfaceThreshold : null;
  return {
    model: typeof fm.model === "string" && fm.model.length > 0 ? fm.model : DEFAULT_MODEL,
    fallbackModel:
      typeof fm.fallbackModel === "string" && fm.fallbackModel.length > 0 ? fm.fallbackModel : FALLBACK_MODEL,
    timeoutMs: typeof fm.timeoutMs === "number" && fm.timeoutMs > 0 ? fm.timeoutMs : DEFAULT_TIMEOUT_MS,
    maxFileBytes: typeof fm.maxFileBytes === "number" && fm.maxFileBytes > 0 ? fm.maxFileBytes : MAX_FILE_BYTES,
    surfaceThreshold:
      surfaceCandidate && VALID_THRESHOLDS.has(surfaceCandidate) ? surfaceCandidate : DEFAULT_SURFACE_THRESHOLD,
    debounceMs: typeof fm.debounceMs === "number" && fm.debounceMs >= 0 ? fm.debounceMs : DEBOUNCE_MS,
    debounceMaxMs: typeof fm.debounceMaxMs === "number" && fm.debounceMaxMs > 0 ? fm.debounceMaxMs : DEBOUNCE_MAX_MS,
  };
}

// Stop marker discovery at the home directory or after 20 levels.
async function findMarkerUp(startDir: string): Promise<string | null> {
  const home = homedir();
  let current = resolve(startDir);
  for (let depth = 0; depth < 20; depth++) {
    const candidate = join(current, MARKER_FILE);
    try {
      await access(candidate);
      return current;
    } catch {
      // not found at this level
    }
    const parent = dirname(current);
    if (parent === current) return null;
    if (current === home) return null;
    current = parent;
  }
  return null;
}

// Keep prompt rendering in the shared module.
function buildPrompt(args: Parameters<typeof buildReviewPrompt>[0]): string {
  return buildReviewPrompt(args);
}

// Pass the prompt on stdin to avoid ARG_MAX for large edited files.
function buildCodexArgs(model: string): string[] {
  const args = ["exec", "--skip-git-repo-check", "--ephemeral"];
  if (process.env.ASK_CODEX_LOAD_USER_CONFIG !== "1") {
    args.push("--ignore-user-config", "--ignore-rules");
  }
  // The reviewer must not mutate the edited workspace.
  args.push(
    "--sandbox",
    "read-only",
    "-c",
    `model_reasoning_effort="${DEFAULT_REASONING_EFFORT}"`,
    "--json",
    "-m",
    model,
  );
  return args;
}

// The final answer is the last completed agent_message in Codex JSONL output.
interface CodexJsonlEvent {
  type?: string;
  item?: { type?: string; text?: unknown };
  message?: unknown;
}

function parseCodexJsonl(stdout: string): string {
  const lines = stdout.split("\n").filter((l) => l.trim().length > 0);
  let lastAgentMessage: string | undefined;
  let lastError: string | undefined;
  for (const line of lines) {
    let parsed: CodexJsonlEvent;
    try {
      parsed = JSON.parse(line);
    } catch {
      continue;
    }
    if (parsed?.type === "item.completed") {
      const item = parsed.item;
      if (item?.type === "agent_message" && typeof item.text === "string" && item.text.length > 0) {
        lastAgentMessage = item.text;
      }
    }
    if (parsed?.type === "error") {
      lastError = JSON.stringify(parsed);
    }
  }
  if (lastError && !lastAgentMessage) {
    throw new Error(`Codex error event: ${lastError}`);
  }
  return lastAgentMessage ?? stdout;
}

function isQuotaError(err: unknown): boolean {
  const msg = (err instanceof Error ? err.message : String(err)).toLowerCase();
  return QUOTA_SIGNALS.some((sig) => msg.includes(sig));
}

function isModelUnavailableError(err: unknown): boolean {
  const msg = (err instanceof Error ? err.message : String(err)).toLowerCase();
  return MODEL_UNAVAILABLE_SIGNALS.some((sig) => msg.includes(sig));
}

// Retry provider transients, never local timeout, parse failure, or quota exhaustion.
function isTransientError(err: unknown): boolean {
  if (err && typeof err === "object" && "verdict" in err) {
    if (err.verdict === "timeout" || err.verdict === "parse_failed") return false;
  }
  if (isQuotaError(err)) return false;
  const msg = err instanceof Error ? err.message : String(err);
  return TRANSIENT_SIGNALS.some((sig) => sig.test(msg));
}

function sleepMs(ms: number): Promise<void> {
  return new Promise((r) => {
    setTimeout(r, ms);
  });
}

// Tag errors for classification without parsing message text.
function taggedError(message: string, verdict: string): ReviewError {
  const err: ReviewError = new Error(message);
  err.verdict = verdict;
  return err;
}

function verdictFromError(err: unknown): string {
  if (
    err &&
    typeof err === "object" &&
    "verdict" in err &&
    typeof err.verdict === "string" &&
    err.verdict in VERDICT_PREFIXES
  ) {
    return err.verdict;
  }
  return "error";
}

// Codex JSONL error events usually carry the failure that stderr omits.
function extractJsonlErrorEvents(stdout: string): string[] {
  const messages: string[] = [];
  for (const line of stdout.split("\n")) {
    if (line.trim().length === 0) continue;
    let parsed: CodexJsonlEvent;
    try {
      parsed = JSON.parse(line);
    } catch {
      continue;
    }
    if (parsed?.type === "error") {
      messages.push(typeof parsed.message === "string" ? parsed.message : JSON.stringify(parsed));
    }
  }
  return messages;
}

// Keep the stderr tail bounded before downstream UTF-8 clamping.
function stderrTail(stderr: string): string {
  const lines = stderr
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0);
  if (lines.length === 0) return "";
  const tail = lines.slice(-3).join(" | ");
  return tail.length > 500 ? tail.slice(-500) : tail;
}

// Pipe and close stdin; Codex otherwise waits indefinitely for more input.
interface CodexCall {
  prompt: string;
  model: string;
  timeoutMs: number;
}

function spawnCodex({ prompt, model, timeoutMs }: CodexCall): Promise<string> {
  return new Promise((resolveCall, rejectCall) => {
    const args = buildCodexArgs(model);
    const child = spawn("codex", args, {
      stdio: ["pipe", "pipe", "pipe"],
      // A POSIX process group lets termination reach Codex descendants.
      detached: !IS_WINDOWS,
    });

    let stdout = "";
    let stderr = "";
    let settled = false;

    child.stdin.on("error", () => {});
    child.stdin.write(prompt);
    child.stdin.end();

    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString();
    });
    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });

    const timer = setTimeout(() => {
      if (settled) return;
      settled = true;
      terminateProcessTree(child, "SIGTERM");
      setTimeout(() => {
        terminateProcessTree(child, "SIGKILL");
      }, 5000);
      rejectCall(taggedError(`codex exec timed out after ${Math.round(timeoutMs / 1000)}s`, "timeout"));
    }, timeoutMs);

    child.on("error", (err) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      rejectCall(taggedError(`failed to spawn codex: ${err.message}`, "spawn_failed"));
    });

    child.on("close", (code) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      if (code === 0) {
        try {
          resolveCall(parseCodexJsonl(stdout));
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          rejectCall(taggedError(msg, "parse_failed"));
        }
      } else {
        // Prefer JSONL errors; stderr often contains only the stdin banner.
        const errorEvents = extractJsonlErrorEvents(stdout);
        const reason =
          errorEvents.length > 0 ? errorEvents[errorEvents.length - 1] : stderrTail(stderr) || `codex exit ${code}`;
        rejectCall(taggedError(reason, "error"));
      }
    });
  });
}

// Jitter the one transient retry to avoid synchronized hook bursts.
async function spawnCodexWithRetry({
  prompt,
  model,
  timeoutMs,
  markerDir,
}: CodexCall & { markerDir: string }): Promise<string> {
  try {
    return await spawnCodex({ prompt, model, timeoutMs });
  } catch (err) {
    if (!isTransientError(err)) throw err;
    const reason = err instanceof Error ? err.message : String(err);
    const delayMs = 1000 + Math.random() * 1500;
    await appendLog(markerDir, {
      timestamp: new Date().toISOString(),
      verdict: "retried",
      reason,
      model,
      delayMs: Math.round(delayMs),
    });
    await sleepMs(delayMs);
    return await spawnCodex({ prompt, model, timeoutMs });
  }
}

// Cache clientInfo for this hook process so handshake metadata remains stable.
let _cachedBrokerClientInfo: { name: string; title: string; version: string } | null = null;
function brokerClientInfo(): { name: string; title: string; version: string } {
  if (_cachedBrokerClientInfo) return _cachedBrokerClientInfo;
  let v = "unknown";
  try {
    const here = dirname(fileURLToPath(import.meta.url));
    const manifest = JSON.parse(readFileSync(join(here, "..", "package.json"), "utf-8"));
    v = manifest?.version || "unknown";
  } catch {
    // best-effort
  }
  _cachedBrokerClientInfo = { name: "codex-pair", title: `codex-pair plugin v${v}`, version: v };
  return _cachedBrokerClientInfo;
}

// Broker connection failures are tagged for direct-review fallback.
async function runWithBroker({
  prompt,
  timeoutMs,
  model,
  markerDir,
}: CodexCall & { markerDir: string }): Promise<string> {
  const state = readBrokerState(markerDir);
  if (!state || !isBrokerDescriptorEligible(state)) {
    const err: ReviewError = new Error("runWithBroker: broker descriptor unavailable");
    err.brokerFailure = true;
    err.brokerPhase = "connect";
    throw err;
  }
  const deadline = Date.now() + timeoutMs;
  // A warm broker must complete its handshake within two seconds, inside its budget.
  const connectMs = Math.min(2000, Math.floor(timeoutMs / 4));
  let connection: Awaited<ReturnType<typeof initializeBroker>>["connection"] | null = null;
  let rpc: Awaited<ReturnType<typeof initializeBroker>>["rpc"];
  try {
    const init = await initializeBroker(state.transportUrl, brokerClientInfo(), {
      handshakeTimeoutMs: connectMs,
      initializeTimeoutMs: connectMs,
    });
    connection = init.connection;
    rpc = init.rpc;
  } catch (caught) {
    const err = caught as ReviewError;
    if (err && typeof err === "object") {
      err.brokerFailure = true;
      err.brokerPhase = err.brokerPhase || "connect";
    }
    throw err;
  }
  try {
    return await submitReview({
      connection,
      rpc,
      cwd: markerDir,
      // The review prompt already contains base instructions.
      baseInstructions: "",
      prompt,
      model,
      effort: DEFAULT_REASONING_EFFORT,
      timeoutMs: Math.max(0, deadline - Date.now()),
    });
  } finally {
    if (connection) {
      try {
        connection.close(1000, "review done");
      } catch {
        // best-effort
      }
    }
  }
}

interface ReviewCall extends CodexCall {
  fallbackModel: string;
  markerDir: string;
}

async function runCodexWithFallback({
  prompt,
  timeoutMs,
  model,
  fallbackModel,
  markerDir,
}: ReviewCall): Promise<{ response: string; fellBack: boolean; viaBroker?: boolean }> {
  // Broker failures retry directly; quota uses the fallback model; transients consume one retry.
  let retryPrimary = true;
  let directTimeoutMs = timeoutMs;
  if (isBrokerEnabled(markerDir)) {
    const deadline = Date.now() + timeoutMs;
    try {
      // Half the budget leaves a stalled broker's direct fallback the rest, so the review fits one timeout.
      return {
        response: await runWithBroker({ prompt, model, timeoutMs: Math.floor(timeoutMs / 2), markerDir }),
        fellBack: false,
        viaBroker: true,
      };
    } catch (caught) {
      const err = caught as ReviewError;
      directTimeoutMs = deadline - Date.now();
      const quota = isQuotaError(err);
      if (!quota && !err?.brokerFailure && !isTransientError(err)) throw err;
      try {
        await appendLog(markerDir, {
          timestamp: new Date().toISOString(),
          verdict: "broker_fallback",
          reason: `${err.brokerPhase || "model"}: ${err.message ?? String(err)}`,
        });
      } catch {
        // best-effort; logging failure must never break the hook
      }
      if (quota) return runFallbackModel(err, { prompt, timeoutMs: directTimeoutMs, model, fallbackModel, markerDir });
      retryPrimary = Boolean(err?.brokerFailure);
    }
  }
  try {
    const call = { prompt, model, timeoutMs: directTimeoutMs, markerDir };
    return {
      response: retryPrimary ? await spawnCodexWithRetry(call) : await spawnCodex(call),
      fellBack: false,
    };
  } catch (err) {
    if (!isQuotaError(err)) throw err;
    return runFallbackModel(err as ReviewError, {
      prompt,
      timeoutMs: directTimeoutMs,
      model,
      fallbackModel,
      markerDir,
    });
  }
}

async function runFallbackModel(
  err: ReviewError,
  { prompt, timeoutMs, model, fallbackModel, markerDir }: ReviewCall,
): Promise<{ response: string; fellBack: boolean }> {
  if (model !== fallbackModel) {
    try {
      const response = await spawnCodexWithRetry({
        prompt,
        model: fallbackModel,
        timeoutMs,
        markerDir,
      });
      return { response, fellBack: true };
    } catch (caught) {
      const fallbackErr = caught as ReviewError;
      // Either quota or an unavailable fallback exhausts the model ladder; preserve the primary reset hint.
      if (isQuotaError(fallbackErr) && fallbackErr && typeof fallbackErr === "object") {
        fallbackErr.quotaExhausted = true;
        throw fallbackErr;
      }
      if (isModelUnavailableError(fallbackErr) && err && typeof err === "object") {
        err.quotaExhausted = true;
        throw err;
      }
      throw fallbackErr;
    }
  }
  // model === fallbackModel: there is no ladder left — quota here IS exhaustion.
  if (err && typeof err === "object") {
    err.quotaExhausted = true;
  }
  throw err;
}

// If worker spawn fails, the caller reviews synchronously.
function spawnDebounceWorker({
  markerDir,
  filePath,
  toolName,
  generation,
  settleMs,
  maxMs,
  sessionId,
}: {
  markerDir: string;
  filePath: string;
  toolName: string;
  generation: number;
  settleMs: number;
  maxMs: number;
  sessionId: string | undefined;
}): boolean {
  try {
    const worker = spawn(process.execPath, [join(SCRIPT_DIR, "codex-pair-debounce-worker.mjs")], {
      detached: true,
      stdio: "ignore",
      env: {
        ...process.env,
        CP_MARKER_DIR: markerDir,
        CP_FILE: filePath,
        CP_TOOL: toolName,
        CP_GENERATION: String(generation),
        CP_SETTLE_MS: String(settleMs),
        CP_MAX_MS: String(maxMs),
        CP_SESSION_ID: sessionId ?? "",
      },
    });
    worker.on("error", () => {});
    worker.unref();
    return true;
  } catch {
    return false;
  }
}

async function main() {
  if (process.env.CODEX_PAIR_DISABLED === "1") process.exit(0);

  const raw = await readStdin();
  let payload: HookInput | undefined;
  try {
    payload = JSON.parse(raw);
  } catch {
    process.exit(0);
  }

  const toolName = payload?.tool_name;
  if (!toolName || !WATCHED_TOOLS.has(toolName)) process.exit(0);

  const filePath = payload?.tool_input?.file_path;
  if (!filePath || typeof filePath !== "string") process.exit(0);

  // Resolve from the edited file so cross-repository edits use the right marker and log.
  markerAnchor = dirname(filePath);
  const markerDir = await findMarkerUp(markerAnchor);
  if (!markerDir) process.exit(0);

  // Register before skip gates so earlier HIGH findings remain visible across repositories.
  registerMarker(payload?.session_id, markerDir);

  const pauseInfo = readPauseInfo(markerDir);
  if (pauseInfo) {
    // Expired auto-pauses resume here; a failed retry may create a new pause.
    const resumeDecision = resolveAutoResume(pauseInfo, {
      now: Date.now(),
      currentVersion: readPluginVersion(),
    });
    // Reread a changed pause sentinel to distinguish concurrent resume from a new pause.
    const resumed = resumeDecision.resume && clearAutoPause(markerDir, pauseInfo);
    const currentPause = resumed ? null : resumeDecision.resume ? readPauseInfo(markerDir) : pauseInfo;
    if (resumed) {
      await appendLog(markerDir, {
        timestamp: new Date().toISOString(),
        tool: toolName,
        file: filePath,
        verdict: "auto_resumed",
        reason: `${resumeDecision.why} (paused ${pauseInfo.at ?? "unknown"}, kind: ${pauseInfo.kind})`,
      });
      noticePrefix = `codex-pair auto-resumed (${resumeDecision.why}): was ${pauseInfo.kind}-paused since ${pauseInfo.at ?? "unknown"}. Reviews are live again.`;
      // fall through — this edit gets reviewed
    } else if (currentPause) {
      const pauseReason = currentPause.manual
        ? "paused via /codex-pair-pause (rm .codex-pair/state/paused to resume)"
        : `auto-paused (${currentPause.kind}${currentPause.resetHint ? `, resets ~${currentPause.resetHint}` : ""}) — resume with /codex-pair-resume`;
      await appendLog(markerDir, {
        timestamp: new Date().toISOString(),
        tool: toolName,
        file: filePath,
        verdict: "skipped",
        reason: pauseReason,
      });
      process.exit(0);
    }
    // A concurrent resume needs no second notice.
  }

  const lower = filePath.toLowerCase();
  if (SKIP_PATTERNS.some((p) => lower.includes(p))) {
    // A skipped edit must still emit a queued auto-resume notice.
    await flushNoticeOnly();
    process.exit(0);
  }

  // Include narrows before ignore excludes; negation-only include rules act as exclusions.
  const includeRules = readIncludeFile(markerDir);
  const positiveInclude = includeRules.filter((r) => !r.negate);
  const includeNegationsAsIgnore = [];
  if (positiveInclude.length > 0) {
    // Standard inclusion gate with full rule set (positive + negation)
    const includeMatch = matchesIgnoreRule(filePath, markerDir, includeRules);
    if (!includeMatch) {
      await appendLog(markerDir, {
        timestamp: new Date().toISOString(),
        tool: toolName,
        file: filePath,
        verdict: "skipped",
        reason: "file not in .codex-pair/include scope",
      });
      await flushNoticeOnly();
      process.exit(0);
    }
  } else if (includeRules.length > 0) {
    // Treat negation-only include rules as exclusions and log the mapping.
    for (const r of includeRules) {
      includeNegationsAsIgnore.push({ negate: false, pattern: r.pattern, raw: r.raw });
    }
    await appendLog(markerDir, {
      timestamp: new Date().toISOString(),
      tool: toolName,
      file: filePath,
      level: "info",
      reason:
        ".codex-pair/include has only negation rules — interpreting as 'review everything except these patterns' (treating as ignore-list entries). Add a positive rule like '**' to use include as a strict allow-list.",
    });
  }

  // Ignored files skip silently with the matching pattern logged.
  const ignoreRulesRaw = readIgnoreFile(markerDir);
  const ignoreRules = [...ignoreRulesRaw, ...includeNegationsAsIgnore];
  const ignoreMatch = matchesIgnoreRule(filePath, markerDir, ignoreRules);
  if (ignoreMatch) {
    await appendLog(markerDir, {
      timestamp: new Date().toISOString(),
      tool: toolName,
      file: filePath,
      verdict: "skipped",
      reason: `matched .codex-pair/ignore: ${ignoreMatch.raw}`,
    });
    await flushNoticeOnly();
    process.exit(0);
  }

  // Parse marker config before applying its file-size limit.
  let projectContext = "";
  let frontmatter = {};
  let frontmatterMalformed = false;
  try {
    const markerContent = await readFile(contextPath(markerDir), "utf8");
    const parsed = parseFrontmatter(markerContent);
    projectContext = parsed.body;
    frontmatter = parsed.frontmatter;
    frontmatterMalformed = parsed.malformed;
  } catch {
    // marker unreadable — proceed with empty context and defaults
  }
  if (frontmatterMalformed) {
    await appendLog(markerDir, {
      timestamp: new Date().toISOString(),
      tool: toolName,
      file: filePath,
      level: "warning",
      reason:
        "malformed frontmatter in .codex-pair/context.md — opener `---` with no matching closer; falling back to defaults",
    });
  }
  const config = resolveConfig(frontmatter);

  // The worker re-invokes forced-sync so the review uses the normal synchronous path.
  const effectiveDebounceMs = process.env.CODEX_PAIR_FORCE_SYNC === "1" ? 0 : config.debounceMs;
  if (effectiveDebounceMs > 0) {
    const record = bumpEditRecord(markerDir, filePath, {
      sessionId: payload?.session_id,
      now: Date.now(),
    });
    if (Math.random() < 0.05) sweepStaleDebounce(markerDir, config.debounceMaxMs);
    const spawned = spawnDebounceWorker({
      markerDir,
      filePath,
      toolName,
      generation: record.generation,
      settleMs: effectiveDebounceMs,
      maxMs: config.debounceMaxMs,
      sessionId: payload?.session_id,
    });
    if (spawned) {
      // Drain pending verdicts only after worker dispatch to avoid double emission.
      const pendingMessages = drainPending(markerDir);
      if (pendingMessages.length > 0) {
        await emitSystemMessage(joinPendingForSurface(pendingMessages));
      } else {
        // A silent exit must still flush a queued auto-resume notice.
        await flushNoticeOnly();
      }
      process.exit(0);
    }
    // On worker spawn failure, consume the debounce record and review synchronously.
    markReviewed(markerDir, filePath, record.generation);
  }

  let fileContent: string;
  try {
    fileContent = await readFile(filePath, "utf8");
  } catch (caught) {
    const err = caught as Error;
    await appendLog(markerDir, {
      timestamp: new Date().toISOString(),
      tool: toolName,
      file: filePath,
      verdict: "skipped",
      reason: `unreadable: ${err.message}`,
    });
    await emitSystemMessage(`codex-pair ${VERDICT_PREFIXES.skipped}: ${filePath} — unreadable (${err.message})`);
    process.exit(0);
  }

  const fileBytes = Buffer.byteLength(fileContent, "utf8");
  // Over-cap files get a partial view rather than losing review coverage.
  let promptContent = fileContent;
  let partialView = false;
  let contextStrategy = "full";
  if (fileBytes > config.maxFileBytes) {
    const adaptive = await buildAdaptiveContext({
      filePath,
      fileContent,
      markerDir,
      maxFileBytes: config.maxFileBytes,
    });
    promptContent = adaptive.content;
    partialView = true;
    contextStrategy = adaptive.strategy;
    await appendLog(markerDir, {
      timestamp: new Date().toISOString(),
      tool: toolName,
      file: filePath,
      level: "info",
      reason: `over-cap (${fileBytes} bytes > ${config.maxFileBytes}); using adaptive context strategy "${contextStrategy}"`,
    });
  }

  const prompt = buildPrompt({
    filePath,
    fileContent: promptContent,
    toolName,
    projectContext,
    partialView,
  });

  const startedAt = Date.now();

  // A content-hash cache hit skips the Codex call.
  const cacheKey = computeCacheKey({
    model: config.model,
    prompt,
    fileContent: promptContent,
    surfaceThreshold: config.surfaceThreshold,
  });
  const cached = await getCachedConcerns(markerDir, cacheKey);
  if (cached) {
    const cachedDurationMs = Date.now() - startedAt;
    await appendLog(markerDir, {
      timestamp: new Date().toISOString(),
      tool: toolName,
      file: filePath,
      verdict: "cached",
      counts: {
        high: cached.high.length,
        med: cached.med.length,
        low: cached.low.length,
      },
      durationMs: cachedDurationMs,
      originalDurationMs: cached.durationMs,
      concerns: {
        high: cached.high.map((c) => c.slice(0, 800)),
        med: cached.med.map((c) => c.slice(0, 800)),
        low: cached.low.map((c) => c.slice(0, 800)),
      },
    });
    // Cache hits must not advance repetition counts; only live reviews do.
    const cachedHashes = [
      ...cached.high.map(hashConcernBody),
      ...cached.med.map(hashConcernBody),
      ...cached.low.map(hashConcernBody),
    ];
    let cachedRepeatedIgnoredCount = 0;
    try {
      const blocking = getBlockingFromShard(markerDir, filePath, cachedHashes);
      cachedRepeatedIgnoredCount = blocking.length;
    } catch {
      // best-effort
    }
    await emitSystemMessage(
      buildVerdictMessage({
        filePath,
        concerns: cached,
        fellBack: false,
        durationMs: cachedDurationMs,
        surfaceThreshold: config.surfaceThreshold,
        cached: true,
        repeatedIgnoredCount: cachedRepeatedIgnoredCount,
        logPath: logPath(markerDir),
      }),
    );
    process.exit(0);
  }

  // Coalesce concurrent reviews of one file without stealing live locks.
  const inflightTtlMs = Math.max(config.timeoutMs, INFLIGHT_TTL_MIN_MS) + 60_000;
  const lockResult = tryAcquireInflightLock(markerDir, filePath, inflightTtlMs);
  if (!lockResult.acquired) {
    await appendLog(markerDir, {
      timestamp: new Date().toISOString(),
      tool: toolName,
      file: filePath,
      verdict: "skipped",
      reason: `coalesced — another review is in-flight for this file (${lockResult.reason})`,
    });
    await flushNoticeOnly();
    process.exit(0);
  }
  const acquiredLockPath = lockResult.lockPath;
  process.on("exit", () => releaseInflightLock(acquiredLockPath));

  let response: string;
  let fellBack = false;
  try {
    // Broker and direct modes share one fallback path.
    const result = await runCodexWithFallback({
      prompt,
      timeoutMs: config.timeoutMs,
      model: config.model,
      fallbackModel: config.fallbackModel,
      markerDir,
    });
    response = result.response;
    fellBack = result.fellBack;
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    const verdict = verdictFromError(err);
    const prefix = VERDICT_PREFIXES[verdict] ?? VERDICT_PREFIXES.error;
    const durationMs = Date.now() - startedAt;

    // Quota exhaustion writes one exclusive pause sentinel and stays silent thereafter.
    if (err && typeof err === "object" && "quotaExhausted" in err && err.quotaExhausted) {
      const resetHint = parseResetHint(reason);
      const paused = writeAutoPause(markerDir, { kind: "quota", reason, resetHint });
      await appendLog(markerDir, {
        timestamp: new Date().toISOString(),
        tool: toolName,
        file: filePath,
        verdict,
        reason,
        durationMs,
        ...(paused ? { autoPaused: "quota" } : {}),
      });
      if (paused) {
        const resetClause = resetHint ? ` (resets ~${resetHint})` : "";
        await emitSystemMessage(
          `codex-pair auto-paused: provider quota exhausted${resetClause}. Resume with /codex-pair-resume.`,
        );
      } else {
        // A silent exit must still flush a queued auto-resume notice.
        await flushNoticeOnly();
      }
      process.exit(0);
    }

    // Persist non-quota failure streaks across sessions to prevent repeated error spam.
    const failureCount = recordReviewFailure(markerDir, reason);
    if (failureCount >= AUTOPAUSE_FAILURE_THRESHOLD) {
      const paused = writeAutoPause(markerDir, { kind: "failures", reason });
      await appendLog(markerDir, {
        timestamp: new Date().toISOString(),
        tool: toolName,
        file: filePath,
        verdict,
        reason,
        durationMs,
        ...(paused ? { autoPaused: "failures" } : {}),
      });
      if (paused) {
        await emitSystemMessage(
          `codex-pair auto-paused after ${AUTOPAUSE_FAILURE_THRESHOLD} consecutive review failures (last: ${reason}). Resume with /codex-pair-resume.`,
        );
      } else {
        // A silent exit must still flush a queued auto-resume notice.
        await flushNoticeOnly();
      }
      process.exit(0);
    }

    await appendLog(markerDir, {
      timestamp: new Date().toISOString(),
      tool: toolName,
      file: filePath,
      verdict,
      reason,
      durationMs,
    });
    await emitSystemMessage(
      `codex-pair ${prefix}: ${filePath} — review failed: ${reason} (${formatDuration(durationMs)}) (failure ${failureCount}/${AUTOPAUSE_FAILURE_THRESHOLD} before auto-pause)`,
    );
    process.exit(0);
  }

  // Live review succeeded — any failure streak is over (#176 backstop).
  clearReviewFailures(markerDir);

  const concerns = parseConcerns(response);
  const total = concerns.high.length + concerns.med.length + concerns.low.length;
  const durationMs = Date.now() - startedAt;

  // Cache-write failure must not break a completed review.
  await setCachedConcerns(markerDir, cacheKey, {
    high: concerns.high,
    med: concerns.med,
    low: concerns.low,
    durationMs,
  });

  await appendLog(markerDir, {
    timestamp: new Date().toISOString(),
    tool: toolName,
    file: filePath,
    verdict: total === 0 ? "none" : "concerns",
    fellBack,
    counts: {
      high: concerns.high.length,
      med: concerns.med.length,
      low: concerns.low.length,
    },
    durationMs,
    concerns: {
      high: concerns.high.map((c) => c.slice(0, 800)),
      med: concerns.med.map((c) => c.slice(0, 800)),
      low: concerns.low.map((c) => c.slice(0, 800)),
    },
  });

  // Count repeated live findings and surface a blocking banner at the threshold.
  const repetitionHashes = [
    ...concerns.high.map(hashConcernBody),
    ...concerns.med.map(hashConcernBody),
    ...concerns.low.map(hashConcernBody),
  ];
  let repeatedIgnoredCount = 0;
  try {
    const blocking = await updateRepetitions(markerDir, filePath, repetitionHashes);
    repeatedIgnoredCount = blocking.length;
  } catch {
    // best-effort — repetitions are advisory; failure must not break the hook
  }

  await emitSystemMessage(
    buildVerdictMessage({
      filePath,
      concerns,
      fellBack,
      durationMs,
      surfaceThreshold: config.surfaceThreshold,
      repeatedIgnoredCount,
      logPath: logPath(markerDir),
    }),
  );

  process.exit(0);
}

main().catch(async (err) => {
  try {
    // Log unhandled failures in the edited file’s repository when its path is known.
    const anchor = markerAnchor ?? process.cwd();
    const markerDir = await findMarkerUp(anchor);
    if (markerDir) {
      await appendLog(markerDir, {
        timestamp: new Date().toISOString(),
        verdict: "error",
        reason: `unhandled: ${err?.message ?? String(err)}`,
      });
    }
  } catch {
    // ignore — nothing more we can do
  }
  process.exit(0);
});
