#!/usr/bin/env node
// Source of truth: codex-pair-session.mts. The sibling .mjs is generated by `yarn workspace @ask-llm/plugin build:hooks`; never edit it.

// Session lifecycle hook. Broker failures must not break per-edit reviews.

import { access } from "node:fs/promises";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { resolveBrokerPreference } from "./lib/broker.mts";
import { bootstrapBroker, teardownBroker } from "./lib/broker-lifecycle.mts";
import { clearAllDebounceState } from "./lib/debounce-state.mts";
import type { HookInput } from "./lib/hook-input.mjs";
import { clearSession } from "./lib/session-registry.mts";
import {
  appendLog,
  CONTEXT_FILENAME,
  clearAutoPause,
  PAIR_ROOT_DIR,
  readPauseInfo,
  readPluginVersion,
  resolveAutoResume,
} from "./lib/state.mts";

const MARKER_FILE = join(PAIR_ROOT_DIR, CONTEXT_FILENAME);

// Keep marker discovery local so marketplace installs need no workspace dependencies.
async function findMarkerUp(startDir: string): Promise<string | null> {
  const home = homedir();
  let current = resolve(startDir);
  for (let depth = 0; depth < 20; depth++) {
    const candidate = join(current, MARKER_FILE);
    try {
      await access(candidate);
      return current;
    } catch {
      // not found here
    }
    const parent = dirname(current);
    if (parent === current) return null;
    if (current === home) return null;
    current = parent;
  }
  return null;
}

async function readStdin(): Promise<string> {
  return new Promise((resolve) => {
    let data = "";
    process.stdin.on("data", (c) => {
      data += c.toString();
    });
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", () => resolve(""));
  });
}

async function handleSessionStart(sessionId: unknown) {
  const cwd = process.cwd();
  const markerDir = await findMarkerUp(cwd);
  if (!markerDir) return; // no opt-in marker, nothing to do
  if (typeof sessionId !== "string" || !sessionId) return;
  await bootstrapBroker(markerDir, { sessionId });
}

async function handleSessionEnd(sessionId: unknown) {
  const cwd = process.cwd();
  const markerDir = await findMarkerUp(cwd);
  if (!markerDir) return;
  // SessionEnd teardown is best-effort; broker failure must not block the session.
  await teardownBroker(markerDir, { sessionId: typeof sessionId === "string" ? sessionId : undefined });
}

async function main() {
  const raw = await readStdin();
  let payload: HookInput | undefined;
  try {
    payload = JSON.parse(raw);
  } catch {
    process.exit(0);
  }

  const event = payload?.hook_event_name;
  if (event !== "SessionStart" && event !== "SessionEnd") {
    process.exit(0);
  }

  // SessionStart reminds the model of active pauses via additionalContext and resumes expired ones.
  if (event === "SessionStart") {
    try {
      const markerDir = await findMarkerUp(process.cwd());
      const pauseInfo = markerDir ? readPauseInfo(markerDir) : null;
      if (markerDir && pauseInfo) {
        const decision = resolveAutoResume(pauseInfo, {
          now: Date.now(),
          currentVersion: readPluginVersion(),
        });
        let context = null;
        // A changed pause sentinel requires rereading current state before notifying.
        if (decision.resume && clearAutoPause(markerDir, pauseInfo)) {
          await appendLog(markerDir, {
            timestamp: new Date().toISOString(),
            verdict: "auto_resumed",
            reason: `${decision.why} (paused ${pauseInfo.at ?? "unknown"}, kind: ${pauseInfo.kind})`,
          });
          context = `codex-pair auto-resumed (${decision.why}): was ${pauseInfo.kind}-paused since ${pauseInfo.at ?? "unknown"}. Reviews are live again.`;
        } else {
          const current = decision.resume ? readPauseInfo(markerDir) : pauseInfo;
          if (current) {
            const since = current.manual ? "" : ` since ${current.at}`;
            const kind = current.manual ? "manually" : `auto (${current.kind})`;
            const reason = current.manual ? "" : ` Reason: ${current.reason}.`;
            context = `codex-pair is paused — ${kind}${since}.${reason} Edits are NOT being reviewed. Resume with /codex-pair-resume.`;
          }
        }
        if (context) {
          await new Promise<void>((resolveWrite) => {
            const out = JSON.stringify({
              hookSpecificOutput: { hookEventName: "SessionStart", additionalContext: context },
            });
            process.stdout.write(`${out}\n`, () => resolveWrite());
          });
        }
      }
    } catch {
      // best-effort (ADR-077) — pause visibility must never break the session
    }
  }

  // Clear debounce state only on SessionEnd; SessionStart could erase a queued verdict.
  if (event === "SessionEnd") {
    const dbMarkerDir = await findMarkerUp(process.cwd());
    if (dbMarkerDir) {
      try {
        clearAllDebounceState(dbMarkerDir);
      } catch {
        // best-effort (ADR-077)
      }
    }
    // Clear the registry by session ID so cwd does not affect cleanup.
    try {
      clearSession(payload?.session_id);
    } catch {
      // best-effort (ADR-077)
    }
  }

  const brokerMarkerDir = await findMarkerUp(process.cwd());
  if (!brokerMarkerDir) process.exit(0);

  try {
    if (event === "SessionStart") {
      if (resolveBrokerPreference(brokerMarkerDir)) await handleSessionStart(payload?.session_id);
      else await teardownBroker(brokerMarkerDir, { onlyIfCredentialMissing: true });
    } else if (event === "SessionEnd") await handleSessionEnd(payload?.session_id);
  } catch {
    // Bootstrap failure must not break the session.
  }
  process.exit(0);
}

main().catch(() => process.exit(0));
