#!/usr/bin/env node
// Source of truth: codex-pair-stop-gate.mts. The sibling .mjs is generated by `yarn workspace @ask-llm/plugin build:hooks`; never edit it.

// The Stop-gate blocks opted-in HIGH findings but fails open on internal errors.

import { execFileSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, realpathSync, statSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { debounceRoot, drainPending, joinPendingForSurface, reviewingRoot } from "./lib/debounce-state.mjs";
import type { HookInput } from "./lib/hook-input.mjs";
import { collectSessionMarkers } from "./lib/session-registry.mjs";
import {
  CONTEXT_FILENAME,
  contextPath,
  INFLIGHT_TTL_MIN_MS,
  inflightRoot,
  logPath,
  PAIR_ROOT_DIR,
  readAcks,
} from "./lib/state.mjs";
import {
  collectBlockingHighs,
  collectInFlight,
  formatBlockMessage,
  formatInFlightMessage,
  parseGitPorcelain,
  selectLatestEntries,
} from "./lib/stop-gate.mjs";

const MARKER_FILE = join(PAIR_ROOT_DIR, CONTEXT_FILENAME);

function findMarkerUp(startDir: string): string | null {
  const home = homedir();
  let current = resolve(startDir);
  for (let depth = 0; depth < 20; depth++) {
    if (existsSync(join(current, MARKER_FILE))) return current;
    const parent = dirname(current);
    if (parent === current || current === home) return null;
    current = parent;
  }
  return null;
}

function readStdin() {
  return new Promise<string>((r) => {
    let data = "";
    process.stdin.on("data", (c) => (data += c.toString()));
    process.stdin.on("end", () => r(data));
    process.stdin.on("error", () => r(""));
  });
}

// Read only the frontmatter scalars needed by the Stop-gate.
function readMarkerScalar(markerDir: string, key: string): string | null {
  let text: string;
  try {
    text = readFileSync(contextPath(markerDir), "utf8");
  } catch {
    return null;
  }
  const fm = text.match(/^---\r?\n([\s\S]*?)\r?\n---/); // tolerate CRLF (Windows)
  if (!fm) return null;
  const m = fm[1].match(new RegExp(`^\\s*${key}:\\s*(\\S+)\\s*$`, "m"));
  return m ? m[1].trim() : null;
}

function readBlockOn(markerDir: string): string | null {
  return readMarkerScalar(markerDir, "blockOn");
}

function gitDirtySet(markerDir: string) {
  // timeout guards against a hung git (locked index, slow FS) wedging turn-end.
  const opts = {
    encoding: "utf8" as const,
    stdio: ["ignore", "pipe", "ignore"] as ("ignore" | "pipe")[],
    timeout: 5000,
  };
  try {
    const repoRoot = execFileSync("git", ["-C", markerDir, "rev-parse", "--show-toplevel"], opts).trim();
    const porcelain = execFileSync("git", ["-C", markerDir, "status", "--porcelain=v1", "-z"], opts);
    return parseGitPorcelain(porcelain, repoRoot);
  } catch {
    return null; // not a repo / git missing / timeout → skip the [B] filter
  }
}

// Use the raw marker path because the watch hook writes in-flight state there.
function readInFlightInputs(markerDir: string) {
  const records = [];
  try {
    const root = debounceRoot(markerDir);
    for (const name of readdirSync(root)) {
      if (!name.endsWith(".json")) continue;
      try {
        records.push(JSON.parse(readFileSync(join(root, name), "utf8")));
      } catch {
        // malformed record — collectInFlight tolerates junk anyway
      }
    }
  } catch {
    // no debounce dir yet
  }
  // Reviewing markers cover the gap between debounce consumption and lock acquisition.
  const lockMtimes = [];
  for (const root of [inflightRoot(markerDir), reviewingRoot(markerDir)]) {
    try {
      for (const name of readdirSync(root)) {
        try {
          lockMtimes.push(statSync(join(root, name)).mtimeMs);
        } catch {
          // entry vanished between readdir and stat
        }
      }
    } catch {
      // dir doesn't exist yet
    }
  }
  return { records, lockMtimes };
}

// Match the watch hook lock TTL so both agree when a review remains in flight.
function inflightFreshMs(markerDir: string): number {
  const fmTimeout = Number(readMarkerScalar(markerDir, "timeoutMs"));
  const timeout =
    Number.isFinite(fmTimeout) && fmTimeout > 0 ? fmTimeout : Number(process.env.ASK_CODEX_TIMEOUT_MS ?? 800_000);
  return Math.max(timeout, INFLIGHT_TTL_MIN_MS) + 60_000;
}

function writeAndExit(obj: unknown): void {
  process.stdout.write(`${JSON.stringify(obj)}\n`, () => process.exit(0));
}

// Canonicalize for git paths; macOS may resolve /var to /private/var.
function canonicalizeEntries<T extends object>(entries: Iterable<[string, T]>): Map<string, T & { file: string }> {
  const out = new Map<string, T & { file: string }>();
  for (const [file, entry] of entries) {
    let real = file;
    try {
      real = realpathSync(file);
    } catch {
      // missing/inaccessible → keep raw; collectBlockingHighs' existsFn drops it
    }
    out.set(real, { ...entry, file: real });
  }
  return out;
}

// Read in-flight state from the raw marker path and canonicalize only for git/log matching.
function evaluateMarker(markerDir: string) {
  // Aggregate raw verdicts before applying the global surface cap.
  const pending = drainPending(markerDir);

  if (readBlockOn(markerDir) !== "HIGH") {
    return { pending, blockReason: null };
  }

  const inFlight = collectInFlight({
    ...readInFlightInputs(markerDir),
    now: Date.now(),
    freshMs: inflightFreshMs(markerDir),
  });

  let canonical = markerDir;
  try {
    canonical = realpathSync(markerDir);
  } catch {
    // keep raw on the rare realpath failure
  }

  let logText = "";
  try {
    logText = readFileSync(logPath(canonical), "utf8");
  } catch {
    // no log yet — an in-flight first-ever review can still block below
  }

  const blocking = collectBlockingHighs({
    entries: canonicalizeEntries(selectLatestEntries(logText)),
    acks: readAcks(canonical),
    existsFn: existsSync,
    gitDirty: gitDirtySet(canonical),
    markerDir: canonical,
  });

  let blockReason = null;
  if (blocking.length > 0) {
    blockReason = formatBlockMessage(blocking, canonical);
    if (inFlight.any) blockReason = `${formatInFlightMessage(inFlight, canonical)}\n\n${blockReason}`;
  } else if (inFlight.any) {
    blockReason = formatInFlightMessage(inFlight, canonical);
  }
  return { pending, blockReason };
}

async function main() {
  const raw = await readStdin();
  let payload: HookInput | undefined;
  try {
    payload = JSON.parse(raw);
  } catch {
    process.exit(0);
  }
  if (payload?.hook_event_name !== "Stop") process.exit(0);
  if (payload?.stop_hook_active) process.exit(0);

  // Include registered sibling repositories even when cwd has no marker.
  const cwdMarker = findMarkerUp(process.cwd());
  const markers = collectSessionMarkers(cwdMarker, payload?.session_id);
  if (markers.length === 0) process.exit(0);

  const allPending = [];
  const blockReasons = [];
  for (const markerDir of markers) {
    const { pending, blockReason } = evaluateMarker(markerDir);
    allPending.push(...pending);
    if (blockReason) blockReasons.push(blockReason);
  }
  // Apply the verdict surface cap once across all markers.
  const pendingCombined = allPending.length > 0 ? joinPendingForSurface(allPending) : null;

  // Any blocking marker blocks the turn; pending text uses the matching Stop output channel.
  if (blockReasons.length > 0) {
    let reason = blockReasons.join("\n\n");
    if (pendingCombined) reason = `${pendingCombined}\n\n${reason}`;
    writeAndExit({ decision: "block", reason });
    return;
  }

  if (pendingCombined) {
    writeAndExit({
      hookSpecificOutput: { hookEventName: "Stop", additionalContext: pendingCombined },
    });
    return;
  }

  process.exit(0);
}

main().catch((err) => {
  process.stderr.write(
    `[codex-pair] WARNING: stop-gate failed (${err?.message ?? err}). Allowing turn end — HIGH findings may remain.\n`,
  );
  process.exit(0);
});
