import { defineConfig } from "tsdown";

export default defineConfig({
  entry: {
    "index": "src/index.ts",
    "cli": "src/cli.ts",
    "machine": "src/machine.ts",
    "cursor": "src/cursorAgent.ts",
    "ask-llm": "src/ask-llm.ts",
    "plugin": "src/plugin.ts",
    "run": "src/run.ts",
    "codex-run": "src/codex-run.ts",
    "grok-run": "src/grok-run.ts",
    "ollama-run": "src/ollama-run.ts",
    "antigravity-run": "src/antigravity-run.ts",
    "brainstorm-run": "src/brainstorm-run.ts",
    "gemini-executor": "src/providers/gemini-executor.ts",
    "gemini-register": "src/providers/gemini-register.ts",
    "codex-executor": "src/providers/codex-executor.ts",
    "codex-register": "src/providers/codex-register.ts",
    "claude-executor": "src/providers/claude-executor.ts",
    "claude-register": "src/providers/claude-register.ts",
    "grok-executor": "src/providers/grok-executor.ts",
    "grok-register": "src/providers/grok-register.ts",
    "ollama-executor": "src/providers/ollama-executor.ts",
    "ollama-register": "src/providers/ollama-register.ts",
    "antigravity-executor": "src/providers/antigravity-executor.ts",
    "antigravity-register": "src/providers/antigravity-register.ts"
},
  format: ["esm"],
  target: "node24",
  sourcemap: true,
  clean: true,
  dts: true,
  fixedExtension: false,
  deps: { alwaysBundle: [/^@ask-llm\//] },
});
