// Source of truth: broker.mts. The sibling .mjs is generated by `yarn workspace @ask-llm/plugin build:hooks`; never edit it.
// Codex app-server broker for codex-pair (ADR-090, ADR-093, ADR-166).
// Unavailable or incompatible brokers fall back to per-edit codex exec.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { createRpcClient } from "./broker-rpc.mjs";
import { connectWebSocket } from "./broker-transport.mjs";
import { parseFrontmatter } from "./frontmatter.mjs";
// State file under <markerDir>/.codex-pair/state/ (ADR-092).
export const BROKER_STATE_FILE = "broker.json";
export const BROKER_HEALTH_TIMEOUT_MS = 2000;
export const BROKER_SOCKET_PREFIX = "codex-pair-broker";
// Protocol version we target. Pinned so a codex CLI upgrade with breaking
// protocol changes is detected at handshake time rather than silently
// producing malformed requests. Verified empirically against codex-cli
// 0.130.0 via `codex app-server generate-json-schema`; ADR-093 documents
// the methods + notification stream we depend on.
export const BROKER_PROTOCOL_VERSION = "v2";
// JSON-RPC client → server methods codex-pair USES (subset of the 75
// available; see ADR-093). Pinning these here documents the contract and
// lets structural tests catch silent drift.
export const JSONRPC_METHODS = Object.freeze({
    INITIALIZE: "initialize",
    THREAD_START: "thread/start",
    TURN_START: "turn/start",
    TURN_INTERRUPT: "turn/interrupt",
    MODEL_LIST: "model/list", // used for health probe (cheap, no side effects)
});
// JSON-RPC server → client notifications codex-pair LISTENS for. Subset
// of the full event stream; we ignore the rest. `TURN_COMPLETED` is the
// terminal event that carries the final agent message (which carries the
// structured verdict when outputSchema is set).
export const JSONRPC_NOTIFICATIONS = Object.freeze({
    TURN_COMPLETED: "turn/completed",
    TURN_STARTED: "turn/started",
    ITEM_AGENT_MESSAGE_DELTA: "item/agentMessage/delta", // streaming text
    THREAD_TOKEN_USAGE_UPDATED: "thread/tokenUsage/updated", // cost tracking
});
// Strict structured output requires every property; nullable fields remain optional in meaning.
export function buildVerdictSchema() {
    return {
        type: "object",
        required: ["verdict", "findings"],
        additionalProperties: false,
        properties: {
            verdict: {
                type: "string",
                enum: ["clean", "concerns"],
                description: "Closed-set verdict (parser.mjs:parseConcernsJson contract).",
            },
            findings: {
                type: "array",
                description: "Use an empty array when verdict is clean.",
                items: {
                    type: "object",
                    required: ["severity", "body", "title", "file", "line_start", "recommendation"],
                    additionalProperties: false,
                    properties: {
                        severity: {
                            type: "string",
                            enum: ["high", "medium", "low"],
                            description: "ADR-077 severity ladder. 'medium' (canonical) — 'med' is a legacy alias.",
                        },
                        body: {
                            type: "string",
                            description: "The concern itself — what's wrong + why it matters + how to fix.",
                        },
                        title: {
                            type: ["string", "null"],
                            description: "Optional short title rendered ahead of the file:line line.",
                        },
                        file: {
                            type: ["string", "null"],
                            description: "File path (optional). Prepended to the rendered concern.",
                        },
                        line_start: {
                            type: ["integer", "null"],
                            description: "Line number (optional). Multi-review M3 hotfix: parser.mjs reads `line_start`, not `line`. Rendered as ':<n>' suffix on file.",
                        },
                        recommendation: {
                            type: ["string", "null"],
                            description: "Optional fix suggestion. Appended on a new line after body.",
                        },
                    },
                },
            },
        },
    };
}
// Read the session broker descriptor; callers validate it before use.
export function readBrokerState(markerDir) {
    return lifecycleReadBrokerDescriptor(markerDir);
}
export function resolveBrokerPreference(markerDir, env = process.env) {
    if (env.ASK_CODEX_BROKER === "0")
        return false;
    try {
        const marker = readFileSync(join(markerDir, ".codex-pair", "context.md"), "utf8");
        return parseFrontmatter(marker).frontmatter.broker !== false;
    }
    catch {
        return false;
    }
}
export function isBrokerDescriptorEligible(state) {
    if (!isIsolatedBrokerHome(state.isolatedHome))
        return false;
    if (!hasCurrentBrokerAuth(state.isolatedHome))
        return false;
    if (state.protocolVersion !== BROKER_PROTOCOL_VERSION)
        return false;
    if (!lifecycleIsPidAlive(state.pid))
        return false;
    return true;
}
export function isBrokerEnabled(markerDir) {
    if (!resolveBrokerPreference(markerDir))
        return false;
    const state = lifecycleReadBrokerDescriptor(markerDir);
    return state !== null && isBrokerDescriptorEligible(state);
}
// Path resolver for the per-marker-dir broker state file. Used by the
// SessionStart hook (writer) and the per-edit hook (reader).
export function brokerStatePath(markerDir, stateDir) {
    return join(markerDir, stateDir, BROKER_STATE_FILE);
}
// Re-exported so hooks import one broker surface; the lifecycle module imports this module's constants.
export { clearStaleBrokerState } from "./broker-lifecycle.mjs";
import { hasCurrentBrokerAuth, isIsolatedBrokerHome, isPidAlive as lifecycleIsPidAlive, readBrokerDescriptorSync as lifecycleReadBrokerDescriptor, } from "./broker-lifecycle.mjs";
// Caller owns the returned connection; any failure rejects so the hook falls back to direct review.
export async function initializeBroker(transportUrl, clientInfo, options = {}) {
    const { handshakeTimeoutMs = 5000, initializeTimeoutMs = 5000 } = options;
    const connection = await (options.connectWebSocket ?? connectWebSocket)(transportUrl, { handshakeTimeoutMs });
    const rpc = (options.createRpcClient ?? createRpcClient)(connection, { defaultTimeoutMs: initializeTimeoutMs });
    try {
        const initializeResult = await rpc.request(JSONRPC_METHODS.INITIALIZE, { clientInfo }, { timeoutMs: initializeTimeoutMs });
        rpc.notify("initialized", {});
        return { connection, rpc, initializeResult };
    }
    catch (err) {
        try {
            connection.close(1011, "initialize failed");
        }
        catch {
            // already torn down
        }
        throw err;
    }
}
// Initializes a fresh connection and completes `model/list`; any failure means unhealthy, never a throw.
export async function probeBrokerHealth(state) {
    if (!state || typeof state.transportUrl !== "string")
        return false;
    let connection;
    let rpc;
    try {
        connection = await connectWebSocket(state.transportUrl, {
            handshakeTimeoutMs: BROKER_HEALTH_TIMEOUT_MS,
        });
        rpc = createRpcClient(connection, { defaultTimeoutMs: BROKER_HEALTH_TIMEOUT_MS });
        // `model/list` requires the connection to have completed `initialize`
        // first per the codex protocol. The PROBE path opens a fresh
        // connection (no broker-side state shared with the long-lived hook
        // connection), so we must initialize here before model/list.
        await rpc.request(JSONRPC_METHODS.INITIALIZE, { clientInfo: { name: "codex-pair-health-probe", title: "codex-pair health probe", version: "0.0.0" } }, { timeoutMs: BROKER_HEALTH_TIMEOUT_MS });
        rpc.notify("initialized", {});
        await rpc.request(JSONRPC_METHODS.MODEL_LIST, undefined, {
            timeoutMs: BROKER_HEALTH_TIMEOUT_MS,
        });
        return true;
    }
    catch {
        return false;
    }
    finally {
        if (connection && !connection.destroyed) {
            try {
                connection.close(1000, "probe done");
            }
            catch {
                // best-effort
            }
        }
    }
}
// Transport failures (timeout, close, socket error) and protocol rejections become broker failures that
// fall back to direct review; other numeric JSON-RPC errors are the model's verdict.
async function brokerRequest(rpc, method, params, timeoutMs, brokerPhase) {
    try {
        return await rpc.request(method, params, { timeoutMs });
    }
    catch (caught) {
        const err = caught;
        const protocolRejection = [-32600, -32601, -32602].includes(err?.code);
        if (err && typeof err === "object" && (typeof err.code !== "number" || protocolRejection) && !err.brokerFailure) {
            err.verdict = "error";
            err.brokerFailure = true;
            err.brokerPhase = protocolRejection ? "protocol" : brokerPhase;
        }
        throw err;
    }
}
export async function submitReview(args) {
    const { rpc, connection, cwd, baseInstructions, prompt, model, timeoutMs = 60_000, abortSignal } = args;
    const effort = args.effort ?? "medium";
    if (!rpc)
        throw new Error("submitReview: rpc client required");
    if (!connection)
        throw new Error("submitReview: connection required");
    if (typeof prompt !== "string" || prompt.length === 0) {
        throw new Error("submitReview: prompt required");
    }
    const deadline = Date.now() + timeoutMs;
    const remaining = () => Math.max(0, deadline - Date.now());
    // 1. thread/start (ephemeral — codex auto-discards after the turn).
    // approvalPolicy: "never" is mandatory for the hook context (no user
    // available to approve interactive prompts). sandbox: "read-only" denies
    // file writes from the reviewer.
    const threadResp = await brokerRequest(rpc, JSONRPC_METHODS.THREAD_START, {
        ephemeral: true,
        cwd,
        baseInstructions,
        model,
        approvalPolicy: "never",
        sandbox: "read-only",
    }, remaining(), "thread_start");
    const threadId = threadResp?.thread?.id;
    if (typeof threadId !== "string") {
        // M4 brokerFailure discriminator: thread_start failures indicate the
        // broker is broken at the protocol layer. Hook falls back to spawnCodex.
        const err = new Error("submitReview: thread/start returned no thread.id");
        err.verdict = "error";
        err.brokerFailure = true;
        err.brokerPhase = "thread_start";
        throw err;
    }
    // 2. Register the turn/completed waiter BEFORE turn/start. Codex can
    // emit turn/completed between the turn/start dispatch and the listener
    // registration if we order them the other way around (brainstorm
    // Risk #1).
    const completionPromise = rpc.waitFor(JSONRPC_NOTIFICATIONS.TURN_COMPLETED, (n) => n.params?.threadId === threadId, remaining());
    completionPromise.catch(() => { });
    let completion;
    try {
        // 3. turn/start. outputSchema constrains the agent's final message to
        // the parser-compatible shape (parser.mjs::parseConcernsJson).
        const turnResp = await brokerRequest(rpc, JSONRPC_METHODS.TURN_START, {
            threadId,
            input: [{ type: "text", text: prompt }],
            outputSchema: buildVerdictSchema(),
            effort,
            // Belt-and-suspenders: also pin turn-level sandbox + deny network.
            sandboxPolicy: { type: "readOnly", networkAccess: false },
        }, remaining(), "turn_start");
        const turnId = turnResp?.turn?.id;
        if (typeof turnId !== "string") {
            // M4 brokerFailure discriminator: turn_start failures = broker protocol
            // is broken. Hook falls back to spawnCodex.
            const err = new Error("submitReview: turn/start returned no turn.id");
            err.verdict = "error";
            err.brokerFailure = true;
            err.brokerPhase = "turn_start";
            throw err;
        }
        // 4. Wire cancellation. abortSignal abort → turn/interrupt + reject.
        let abortHandler = null;
        let interruptSent = false;
        // Multi-review M3 hotfix: track completion so a late abort (firing
        // AFTER completion resolves but BEFORE finally cleans up) doesn't
        // send a spurious turn/interrupt for an already-done turn.
        let completed = false;
        const abortPromise = abortSignal
            ? new Promise((_, reject) => {
                abortHandler = () => {
                    // Early-return if we already got the completion. Closes the
                    // abort-after-completion race window flagged in multi-review.
                    if (completed)
                        return;
                    interruptSent = true;
                    // Best-effort interrupt; don't await it on the abort path —
                    // we want to reject the user-facing promise immediately.
                    rpc.request(JSONRPC_METHODS.TURN_INTERRUPT, { threadId, turnId }, { timeoutMs: 2000 }).catch(() => { });
                    // Multi-review M3 hotfix: use `verdict` not `code` — the
                    // hook's verdictFromError reads err.verdict. "aborted" is
                    // not in VERDICT_PREFIXES so map to "error".
                    const err = new Error("submitReview: aborted");
                    err.verdict = "error";
                    err.aborted = true; // structured marker for callers who care
                    reject(err);
                };
                if (abortSignal.aborted)
                    abortHandler();
                else
                    abortSignal.addEventListener("abort", abortHandler);
            })
            : null;
        // 5. Race the completion against the abort.
        try {
            completion = abortPromise ? await Promise.race([completionPromise, abortPromise]) : await completionPromise;
            completed = true;
        }
        catch (caught) {
            const err = caught;
            // On timeout (waitFor rejects), send best-effort interrupt so we
            // don't leak a server-side turn. Multi-review M3 hotfix: use the
            // structured err.timeout marker from broker-rpc, not regex on message.
            if (!interruptSent && err && err.timeout === true) {
                rpc.request(JSONRPC_METHODS.TURN_INTERRUPT, { threadId, turnId }, { timeoutMs: 2000 }).catch(() => { });
                const wrapped = new Error("submitReview: turn timed out");
                wrapped.verdict = "timeout";
                wrapped.timeout = true;
                wrapped.brokerFailure = true;
                wrapped.brokerPhase = "turn_completion";
                throw wrapped;
            }
            if (err && typeof err === "object" && !err.aborted) {
                err.brokerFailure = true;
                err.brokerPhase = "turn_completion";
            }
            throw err;
        }
        finally {
            if (abortHandler && abortSignal) {
                abortSignal.removeEventListener("abort", abortHandler);
            }
            // If the abort handler already fired but we'd completed, it sent a
            // spurious interrupt and rejected an unawaited promise. The flag
            // above prevents that — abortHandler now early-returns if completed.
        }
    }
    finally {
        completionPromise.cancel?.();
    }
    // 6. Extract the final agentMessage from `turn.items`. Brainstorm
    // confirmed multiple `agentMessage` items can appear (reasoning summaries
    // vs final answer); `findLast` picks the last/final one.
    // `completed` is read by the abortHandler closure to detect the
    // abort-after-completion race; biome won't strip it.
    const turn = completion?.params?.turn;
    if (!turn || !Array.isArray(turn.items)) {
        // M4: protocol-layer failure → brokerFailure → hook falls back.
        const err = new Error("submitReview: turn/completed missing turn.items");
        err.verdict = "parse_failed";
        err.brokerFailure = true;
        err.brokerPhase = "protocol";
        throw err;
    }
    if (turn.status === "failed" || turn.status === "interrupted") {
        const err = new Error(`submitReview: turn ${turn.status}${turn.error?.message ? ` — ${turn.error.message}` : ""}`);
        err.verdict = "error";
        if (turn.status === "failed" &&
            /invalid_json_schema|unsupported method|method not found|invalid params/i.test(turn.error?.message ?? "")) {
            err.brokerFailure = true;
            err.brokerPhase = "protocol";
        }
        throw err;
    }
    const finalMessage = turn.items.findLast?.((i) => i?.type === "agentMessage");
    if (!finalMessage || typeof finalMessage.text !== "string") {
        // M4: protocol-layer failure (broker spoke turn/completed but with no
        // agentMessage). Mark brokerFailure so hook falls back to spawnCodex —
        // this is a broker-broken state, not a real codex result.
        const err = new Error("submitReview: turn/completed has no agentMessage item");
        err.verdict = "parse_failed";
        err.brokerFailure = true;
        err.brokerPhase = "protocol";
        throw err;
    }
    return finalMessage.text;
}
