// Source of truth: broker.mts. The sibling .mjs is generated by `yarn workspace @ask-llm/plugin build:hooks`; never edit it.
// Unavailable or incompatible app-server brokers fall back to per-edit Codex.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { createRpcClient } from "./broker-rpc.mjs";
import { connectWebSocket } from "./broker-transport.mjs";
import { parseFrontmatter } from "./frontmatter.mjs";
// State file under <markerDir>/.codex-pair/state/ (ADR-092).
export const BROKER_STATE_FILE = "broker.json";
export const BROKER_HEALTH_TIMEOUT_MS = 2000;
export const BROKER_SOCKET_PREFIX = "codex-pair-broker";
// Pin the app-server protocol version so incompatible upgrades fail the handshake.
export const BROKER_PROTOCOL_VERSION = "v2";
export const JSONRPC_METHODS = Object.freeze({
    INITIALIZE: "initialize",
    THREAD_START: "thread/start",
    TURN_START: "turn/start",
    TURN_INTERRUPT: "turn/interrupt",
    MODEL_LIST: "model/list", // used for health probe (cheap, no side effects)
});
// turn/completed carries the final agent message and structured verdict.
export const JSONRPC_NOTIFICATIONS = Object.freeze({
    TURN_COMPLETED: "turn/completed",
    TURN_STARTED: "turn/started",
    ITEM_AGENT_MESSAGE_DELTA: "item/agentMessage/delta", // streaming text
    THREAD_TOKEN_USAGE_UPDATED: "thread/tokenUsage/updated", // cost tracking
});
// Strict structured output requires every property; nullable fields remain optional in meaning.
export function buildVerdictSchema() {
    return {
        type: "object",
        required: ["verdict", "findings"],
        additionalProperties: false,
        properties: {
            verdict: {
                type: "string",
                enum: ["clean", "concerns"],
                description: "Closed-set verdict (parser.mjs:parseConcernsJson contract).",
            },
            findings: {
                type: "array",
                description: "Use an empty array when verdict is clean.",
                items: {
                    type: "object",
                    required: ["severity", "body", "title", "file", "line_start", "recommendation"],
                    additionalProperties: false,
                    properties: {
                        severity: {
                            type: "string",
                            enum: ["high", "medium", "low"],
                            description: "ADR-077 severity ladder. 'medium' (canonical) — 'med' is a legacy alias.",
                        },
                        body: {
                            type: "string",
                            description: "The concern itself — what's wrong + why it matters + how to fix.",
                        },
                        title: {
                            type: ["string", "null"],
                            description: "Optional short title rendered ahead of the file:line line.",
                        },
                        file: {
                            type: ["string", "null"],
                            description: "File path (optional). Prepended to the rendered concern.",
                        },
                        line_start: {
                            type: ["integer", "null"],
                            description: "Line number (optional). Multi-review M3 hotfix: parser.mjs reads `line_start`, not `line`. Rendered as ':<n>' suffix on file.",
                        },
                        recommendation: {
                            type: ["string", "null"],
                            description: "Optional fix suggestion. Appended on a new line after body.",
                        },
                    },
                },
            },
        },
    };
}
// Read the session broker descriptor; callers validate it before use.
export function readBrokerState(markerDir) {
    return lifecycleReadBrokerDescriptor(markerDir);
}
export function resolveBrokerPreference(markerDir, env = process.env) {
    if (env.ASK_CODEX_BROKER !== "1")
        return false;
    try {
        const marker = readFileSync(join(markerDir, ".codex-pair", "context.md"), "utf8");
        return parseFrontmatter(marker).frontmatter.broker !== false;
    }
    catch {
        return false;
    }
}
export function isBrokerDescriptorEligible(state) {
    if (!isIsolatedBrokerHome(state.isolatedHome))
        return false;
    if (!hasCurrentBrokerAuth(state.isolatedHome))
        return false;
    if (state.protocolVersion !== BROKER_PROTOCOL_VERSION)
        return false;
    if (!lifecycleIsPidAlive(state.pid))
        return false;
    return true;
}
export function isBrokerEnabled(markerDir) {
    if (!resolveBrokerPreference(markerDir))
        return false;
    const state = lifecycleReadBrokerDescriptor(markerDir);
    return state !== null && isBrokerDescriptorEligible(state);
}
export function brokerStatePath(markerDir, stateDir) {
    return join(markerDir, stateDir, BROKER_STATE_FILE);
}
// Re-exported so hooks import one broker surface; the lifecycle module imports this module's constants.
export { clearStaleBrokerState } from "./broker-lifecycle.mjs";
import { hasCurrentBrokerAuth, isIsolatedBrokerHome, isPidAlive as lifecycleIsPidAlive, readBrokerDescriptorSync as lifecycleReadBrokerDescriptor, } from "./broker-lifecycle.mjs";
// Caller owns the returned connection; any failure rejects so the hook falls back to direct review.
export async function initializeBroker(transportUrl, clientInfo, options = {}) {
    const { handshakeTimeoutMs = 5000, initializeTimeoutMs = 5000 } = options;
    const connection = await (options.connectWebSocket ?? connectWebSocket)(transportUrl, { handshakeTimeoutMs });
    const rpc = (options.createRpcClient ?? createRpcClient)(connection, { defaultTimeoutMs: initializeTimeoutMs });
    try {
        const initializeResult = await rpc.request(JSONRPC_METHODS.INITIALIZE, { clientInfo }, { timeoutMs: initializeTimeoutMs });
        rpc.notify("initialized", {});
        return { connection, rpc, initializeResult };
    }
    catch (err) {
        try {
            connection.close(1011, "initialize failed");
        }
        catch {
            // already torn down
        }
        throw err;
    }
}
// Initializes a fresh connection and completes `model/list`; any failure means unhealthy, never a throw.
export async function probeBrokerHealth(state) {
    if (!state || typeof state.transportUrl !== "string")
        return false;
    let connection;
    let rpc;
    try {
        connection = await connectWebSocket(state.transportUrl, {
            handshakeTimeoutMs: BROKER_HEALTH_TIMEOUT_MS,
        });
        rpc = createRpcClient(connection, { defaultTimeoutMs: BROKER_HEALTH_TIMEOUT_MS });
        // Initialize each probe connection before model/list.
        await rpc.request(JSONRPC_METHODS.INITIALIZE, { clientInfo: { name: "codex-pair-health-probe", title: "codex-pair health probe", version: "0.0.0" } }, { timeoutMs: BROKER_HEALTH_TIMEOUT_MS });
        rpc.notify("initialized", {});
        await rpc.request(JSONRPC_METHODS.MODEL_LIST, undefined, {
            timeoutMs: BROKER_HEALTH_TIMEOUT_MS,
        });
        return true;
    }
    catch {
        return false;
    }
    finally {
        if (connection && !connection.destroyed) {
            try {
                connection.close(1000, "probe done");
            }
            catch {
                // best-effort
            }
        }
    }
}
// Transport and protocol failures fall back; numeric model errors keep their meaning.
async function brokerRequest(rpc, method, params, timeoutMs, brokerPhase) {
    try {
        return await rpc.request(method, params, { timeoutMs });
    }
    catch (caught) {
        const err = caught;
        const protocolRejection = [-32600, -32601, -32602].includes(err?.code);
        if (err && typeof err === "object" && (typeof err.code !== "number" || protocolRejection) && !err.brokerFailure) {
            err.verdict = "error";
            err.brokerFailure = true;
            err.brokerPhase = protocolRejection ? "protocol" : brokerPhase;
        }
        throw err;
    }
}
export async function submitReview(args) {
    const { rpc, connection, cwd, baseInstructions, prompt, model, timeoutMs = 60_000, abortSignal } = args;
    const effort = args.effort ?? "medium";
    if (!rpc)
        throw new Error("submitReview: rpc client required");
    if (!connection)
        throw new Error("submitReview: connection required");
    if (typeof prompt !== "string" || prompt.length === 0) {
        throw new Error("submitReview: prompt required");
    }
    const deadline = Date.now() + timeoutMs;
    const remaining = () => Math.max(0, deadline - Date.now());
    // Hook reviews use ephemeral read-only threads with no interactive approvals.
    const threadResp = await brokerRequest(rpc, JSONRPC_METHODS.THREAD_START, {
        ephemeral: true,
        cwd,
        baseInstructions,
        model,
        approvalPolicy: "never",
        sandbox: "read-only",
    }, remaining(), "thread_start");
    const threadId = threadResp?.thread?.id;
    if (typeof threadId !== "string") {
        // Thread-start failure means the broker protocol is unusable.
        const err = new Error("submitReview: thread/start returned no thread.id");
        err.verdict = "error";
        err.brokerFailure = true;
        err.brokerPhase = "thread_start";
        throw err;
    }
    // Register completion before turn/start to avoid missing a fast terminal event.
    const completionPromise = rpc.waitFor(JSONRPC_NOTIFICATIONS.TURN_COMPLETED, (n) => n.params?.threadId === threadId, remaining());
    completionPromise.catch(() => { });
    let completion;
    try {
        // Constrain output to the parser-compatible verdict shape.
        const turnResp = await brokerRequest(rpc, JSONRPC_METHODS.TURN_START, {
            threadId,
            input: [{ type: "text", text: prompt }],
            outputSchema: buildVerdictSchema(),
            effort,
            // Belt-and-suspenders: also pin turn-level sandbox + deny network.
            sandboxPolicy: { type: "readOnly", networkAccess: false },
        }, remaining(), "turn_start");
        const turnId = turnResp?.turn?.id;
        if (typeof turnId !== "string") {
            // Turn-start failure means the broker protocol is unusable.
            const err = new Error("submitReview: turn/start returned no turn.id");
            err.verdict = "error";
            err.brokerFailure = true;
            err.brokerPhase = "turn_start";
            throw err;
        }
        // 4. Wire cancellation. abortSignal abort → turn/interrupt + reject.
        let abortHandler = null;
        let interruptSent = false;
        // Track completion so a late abort cannot interrupt a finished turn.
        let completed = false;
        const abortPromise = abortSignal
            ? new Promise((_, reject) => {
                abortHandler = () => {
                    // A completed turn must ignore late aborts.
                    if (completed)
                        return;
                    interruptSent = true;
                    // Reject abort promptly; interrupt is best-effort.
                    rpc.request(JSONRPC_METHODS.TURN_INTERRUPT, { threadId, turnId }, { timeoutMs: 2000 }).catch(() => { });
                    // Use the verdict field consumed by verdictFromError.
                    const err = new Error("submitReview: aborted");
                    err.verdict = "error";
                    err.aborted = true; // structured marker for callers who care
                    reject(err);
                };
                if (abortSignal.aborted)
                    abortHandler();
                else
                    abortSignal.addEventListener("abort", abortHandler);
            })
            : null;
        // 5. Race the completion against the abort.
        try {
            completion = abortPromise ? await Promise.race([completionPromise, abortPromise]) : await completionPromise;
            completed = true;
        }
        catch (caught) {
            const err = caught;
            // Timeout interrupts the server turn; use the RPC timeout marker.
            if (!interruptSent && err && err.timeout === true) {
                rpc.request(JSONRPC_METHODS.TURN_INTERRUPT, { threadId, turnId }, { timeoutMs: 2000 }).catch(() => { });
                const wrapped = new Error("submitReview: turn timed out");
                wrapped.verdict = "timeout";
                wrapped.timeout = true;
                wrapped.brokerFailure = true;
                wrapped.brokerPhase = "turn_completion";
                throw wrapped;
            }
            if (err && typeof err === "object" && !err.aborted) {
                err.brokerFailure = true;
                err.brokerPhase = "turn_completion";
            }
            throw err;
        }
        finally {
            if (abortHandler && abortSignal) {
                abortSignal.removeEventListener("abort", abortHandler);
            }
        }
    }
    finally {
        completionPromise.cancel?.();
    }
    // Use the last agentMessage because a turn may emit multiple messages.
    const turn = completion?.params?.turn;
    if (!turn || !Array.isArray(turn.items)) {
        // M4: protocol-layer failure → brokerFailure → hook falls back.
        const err = new Error("submitReview: turn/completed missing turn.items");
        err.verdict = "parse_failed";
        err.brokerFailure = true;
        err.brokerPhase = "protocol";
        throw err;
    }
    if (turn.status === "failed" || turn.status === "interrupted") {
        const err = new Error(`submitReview: turn ${turn.status}${turn.error?.message ? ` — ${turn.error.message}` : ""}`);
        err.verdict = "error";
        if (turn.status === "failed" &&
            /invalid_json_schema|unsupported method|method not found|invalid params/i.test(turn.error?.message ?? "")) {
            err.brokerFailure = true;
            err.brokerPhase = "protocol";
        }
        throw err;
    }
    const finalMessage = turn.items.findLast?.((i) => i?.type === "agentMessage");
    if (!finalMessage || typeof finalMessage.text !== "string") {
        // Missing agentMessage is a protocol failure that permits direct fallback.
        const err = new Error("submitReview: turn/completed has no agentMessage item");
        err.verdict = "parse_failed";
        err.brokerFailure = true;
        err.brokerPhase = "protocol";
        throw err;
    }
    return finalMessage.text;
}
