// Source of truth: debounce-state.mts. The sibling .mjs is generated by `yarn workspace @ask-llm/plugin build:hooks`; never edit it.

// Per-file edit-debounce state under .codex-pair/state/ (design 2026-06-03); every write is best-effort (ADR-077).

import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, renameSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { stateRoot } from "./state.mts";

export interface EditRecord {
  file: string;
  generation: number;
  burstStartedAt: number;
  reviewedGen: number;
  sessionId?: string;
}

export const DEBOUNCE_DIR = "debounce";
export const PENDING_DIR = "pending";
export const REVIEWED_DIR = "reviewed";
export const DEFAULT_DEBOUNCE_MS = 15_000;
export const DEFAULT_DEBOUNCE_MAX_MS = 60_000;
export const DEBOUNCE_STALE_BUFFER_MS = 300_000;

export const debounceRoot = (markerDir: string): string => join(stateRoot(markerDir), DEBOUNCE_DIR);
export const pendingRoot = (markerDir: string): string => join(stateRoot(markerDir), PENDING_DIR);
export const reviewedRoot = (markerDir: string): string => join(stateRoot(markerDir), REVIEWED_DIR);

function fileHash(file: string): string {
  return createHash("sha256").update(String(file)).digest("hex").slice(0, 16);
}
export const debounceRecordPath = (markerDir: string, file: string): string =>
  join(debounceRoot(markerDir), `${fileHash(file)}.json`);
export const pendingPath = (markerDir: string, file: string): string =>
  join(pendingRoot(markerDir), `${fileHash(file)}.json`);
export const reviewedPath = (markerDir: string, file: string): string =>
  join(reviewedRoot(markerDir), `${fileHash(file)}.json`);

export const contentHash = (text: string): string => createHash("sha256").update(text).digest("hex");

export function fileContentHash(file: string): string | null {
  try {
    return contentHash(readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}

function readReviewedGen(markerDir: string, file: string): number {
  try {
    const { reviewedGen } = JSON.parse(readFileSync(reviewedPath(markerDir, file), "utf8"));
    return Number.isFinite(reviewedGen) ? reviewedGen : 0;
  } catch {
    return 0;
  }
}

// Pre-upgrade edit records carried reviewedGen themselves, so it still floors the done-marker.
const withReviewedGen = (markerDir: string, rec: EditRecord): EditRecord => ({
  ...rec,
  reviewedGen: Math.max(readReviewedGen(markerDir, rec.file), rec.reviewedGen ?? 0),
});

function writeAtomicSync(p: string, value: unknown): void {
  try {
    mkdirSync(dirname(p), { recursive: true });
    const tmp = `${p}.tmp.${process.pid}`;
    writeFileSync(tmp, JSON.stringify(value));
    renameSync(tmp, p);
  } catch {
    // best-effort (ADR-077)
  }
}

// Hooks own the edit record; the done-marker in reviewed/ belongs to the lock holder (one writer per file).
export function bumpEditRecord(
  markerDir: string,
  file: string,
  { sessionId, now }: { sessionId?: string; now: number },
): EditRecord {
  let prev: EditRecord | null = null;
  try {
    prev = JSON.parse(readFileSync(debounceRecordPath(markerDir, file), "utf8"));
  } catch {
    prev = null;
  }
  const reviewedGen = readReviewedGen(markerDir, file);
  // A swept edit record must not restart below the done-marker.
  const generation = Math.max(prev?.generation ?? 0, reviewedGen) + 1;
  const burstInProgress = prev && reviewedGen < prev.generation;
  const burstStartedAt = burstInProgress ? (prev as EditRecord).burstStartedAt : now;
  const record = { file, generation, burstStartedAt, sessionId };
  writeAtomicSync(debounceRecordPath(markerDir, file), record);
  return { ...record, reviewedGen };
}

export function readEditRecord(markerDir: string, file: string): EditRecord | null {
  try {
    return withReviewedGen(markerDir, JSON.parse(readFileSync(debounceRecordPath(markerDir, file), "utf8")));
  } catch {
    return null;
  }
}

export function readDebounceRecords(markerDir: string): EditRecord[] {
  const root = debounceRoot(markerDir);
  const records: EditRecord[] = [];
  let names: string[];
  try {
    names = readdirSync(root);
  } catch {
    return records;
  }
  for (const name of names) {
    if (!name.endsWith(".json")) continue;
    try {
      records.push(withReviewedGen(markerDir, JSON.parse(readFileSync(join(root, name), "utf8"))));
    } catch {
      // malformed record
    }
  }
  return records;
}

export function decideReview({
  record,
  myGeneration,
  now,
  maxMs,
}: {
  record: EditRecord | null;
  myGeneration: number;
  now: number;
  maxMs: number;
}): { review: boolean; reason: string } {
  if (!record) return { review: false, reason: "record-missing" };
  if (record.reviewedGen >= myGeneration) return { review: false, reason: "already-reviewed" };
  if (record.generation === myGeneration) return { review: true, reason: "settled" };
  if (now - record.burstStartedAt >= maxMs) return { review: true, reason: "max-cap" };
  return { review: false, reason: "superseded" };
}

// A cap-triggered worker advances only to its own generation, so the latest worker still reviews the settled state.
export function markReviewed(markerDir: string, file: string, generation: number): void {
  // Callers hold the per-file inflight lock, so read-then-write stays monotonic.
  if (readReviewedGen(markerDir, file) < generation) {
    writeAtomicSync(reviewedPath(markerDir, file), { file, reviewedGen: generation });
  }
}

export function writePending(markerDir: string, file: string, message: string, reviewedContentHash: string): void {
  writeAtomicSync(pendingPath(markerDir, file), { file, message, contentHash: reviewedContentHash });
}

let noticeCounter = 0;
export function writePendingNotice(markerDir: string, message: string): void {
  const name = `notice-${Date.now()}-${process.pid}-${noticeCounter++}.json`;
  writeAtomicSync(join(pendingRoot(markerDir), name), { message, notice: true });
}

// Notices always surface; a verdict surfaces only while the content it reviewed is still on disk.
export function drainPending(markerDir: string): string[] {
  const root = pendingRoot(markerDir);
  const messages: string[] = [];
  let names: string[];
  try {
    names = readdirSync(root);
  } catch {
    return messages;
  }
  for (const name of names) {
    if (!name.endsWith(".json")) continue;
    // Claim by rename so a verdict written after the claim survives and concurrent drains never double-surface.
    const claimed = `${join(root, name)}.${process.pid}.claimed`;
    try {
      renameSync(join(root, name), claimed);
    } catch {
      continue;
    }
    try {
      const entry = JSON.parse(readFileSync(claimed, "utf8"));
      const current =
        entry.notice === true ||
        (typeof entry.contentHash === "string" && entry.contentHash === fileContentHash(entry.file));
      if (current && typeof entry.message === "string" && entry.message.length > 0) messages.push(entry.message);
    } catch {
      // skip malformed
    }
    try {
      unlinkSync(claimed);
    } catch {
      // already gone
    }
  }
  return messages;
}

// Caps only the surfaced text; the overflow stays in the log.
export const MAX_SURFACE_VERDICTS = 8;
export function joinPendingForSurface(messages: string[]): string {
  if (messages.length <= MAX_SURFACE_VERDICTS) return messages.join("\n\n");
  const extra = messages.length - MAX_SURFACE_VERDICTS;
  return `${messages
    .slice(0, MAX_SURFACE_VERDICTS)
    .join("\n\n")}\n\n[codex-pair] +${extra} more verdict(s) drained — see .codex-pair/log.jsonl`;
}

// Orphaned sleepers self-cancel once their record is gone (decideReview → record-missing).
export function clearAllDebounceState(markerDir: string): void {
  for (const root of [debounceRoot(markerDir), pendingRoot(markerDir), reviewedRoot(markerDir)]) {
    let names: string[];
    try {
      names = readdirSync(root);
    } catch {
      continue;
    }
    for (const name of names) {
      try {
        unlinkSync(join(root, name));
      } catch {
        // best-effort
      }
    }
  }
}

// Also removes .claimed pending files left by a drain that crashed mid-read.
export function sweepStaleDebounce(markerDir: string, maxMs: number): void {
  const cutoff = Date.now() - (maxMs + DEBOUNCE_STALE_BUFFER_MS);
  for (const root of [debounceRoot(markerDir), pendingRoot(markerDir), reviewedRoot(markerDir)]) {
    let names: string[];
    try {
      names = readdirSync(root);
    } catch {
      continue;
    }
    for (const name of names) {
      const full = join(root, name);
      try {
        if (statSync(full).mtimeMs < cutoff) unlinkSync(full);
      } catch {
        // skip
      }
    }
  }
}
