// Source of truth: parser.mts. The sibling .mjs is generated by `yarn workspace @ask-llm/plugin build:hooks`; never edit it.

// Concern parsing (ADR-083 JSON contract with a legacy regex fallback) and verdict-message formatting.

export interface Concerns {
  high: string[];
  med: string[];
  low: string[];
}

export const VERDICT_PREFIXES: Record<string, string> = {
  none: "OK",
  concerns: "WARN",
  skipped: "SKIP",
  error: "ERROR",
  spawn_failed: "SPAWN_FAILED",
  timeout: "TIMEOUT",
  parse_failed: "PARSE_FAILED",
  cached: "CACHED",
};

export const SEVERITY_TO_BUCKET: Record<string, keyof Concerns> = {
  high: "high",
  medium: "med",
  med: "med",
  low: "low",
};

export const VALID_THRESHOLDS = new Set(["high", "med", "low"]);
export const DEFAULT_SURFACE_THRESHOLD = "med";

export function formatDuration(durationMs: number): string {
  return `${(durationMs / 1000).toFixed(1)}s`;
}

// LOW stays log-only unless surfaceThreshold is "low" (ADR-077); repeated ignored findings get a banner (ADR-096).
export function buildVerdictMessage({
  filePath,
  concerns,
  fellBack,
  durationMs,
  surfaceThreshold,
  cached,
  repeatedIgnoredCount = 0,
  logPath,
}: {
  filePath: string;
  concerns: Concerns;
  fellBack: boolean;
  durationMs: number;
  surfaceThreshold: string;
  cached?: boolean;
  repeatedIgnoredCount?: number;
  logPath?: string;
}): string {
  const threshold = VALID_THRESHOLDS.has(surfaceThreshold) ? surfaceThreshold : DEFAULT_SURFACE_THRESHOLD;
  const total = concerns.high.length + concerns.med.length + concerns.low.length;
  const flag = fellBack ? " [fallback model]" : "";
  const cachedTag = cached ? " [cached]" : "";
  const logPointer = logPath ? ` → see ${logPath}` : "";
  if (total === 0) {
    return `codex-pair ${VERDICT_PREFIXES.none}${flag}${cachedTag}: ${filePath} — no concerns (${formatDuration(durationMs)})${logPointer}`;
  }
  const counts = `${concerns.high.length}H / ${concerns.med.length}M / ${concerns.low.length}L`;
  const header = `codex-pair ${VERDICT_PREFIXES.concerns}${flag}${cachedTag}: ${filePath} — ${counts} (${formatDuration(durationMs)})${logPointer}`;
  const details: string[] = [];
  for (const c of concerns.high) details.push(`[HIGH]\n${c}`);
  if (threshold === "med" || threshold === "low") {
    for (const c of concerns.med) details.push(`[MED]\n${c}`);
  }
  if (threshold === "low") {
    for (const c of concerns.low) details.push(`[LOW]\n${c}`);
  }
  const body = details.length > 0 ? `${header}\n\n${details.join("\n\n")}` : header;
  if (repeatedIgnoredCount > 0) {
    const banner = [
      "🛑 ═══════════════════════════════════════════════════════════════",
      `🛑 REPEATED-IGNORED FINDING — ${repeatedIgnoredCount} concern${repeatedIgnoredCount === 1 ? " has" : "s have"} been flagged 3+ times`,
      "🛑 without being fixed. This is no longer advisory — please address",
      "🛑 the concerns below BEFORE continuing edits on this file.",
      "🛑 ═══════════════════════════════════════════════════════════════",
      "",
    ].join("\n");
    return banner + body;
  }
  return body;
}

// Raw parse, then fenced block, then the first balanced top-level object (string-aware).
export function tryExtractJson(message: string): unknown {
  const trimmed = message.trim();
  if (trimmed.length === 0) return null;
  try {
    return JSON.parse(trimmed);
  } catch {}
  const fenceMatch = trimmed.match(/^```(?:json)?\s*\n([\s\S]*?)\n```\s*$/i);
  if (fenceMatch) {
    try {
      return JSON.parse(fenceMatch[1]);
    } catch {}
  }
  const start = trimmed.indexOf("{");
  if (start !== -1) {
    let depth = 0;
    let inString = false;
    let escaped = false;
    for (let i = start; i < trimmed.length; i++) {
      const ch = trimmed[i];
      if (escaped) {
        escaped = false;
        continue;
      }
      if (ch === "\\" && inString) {
        escaped = true;
        continue;
      }
      if (ch === '"') inString = !inString;
      else if (!inString && ch === "{") depth++;
      else if (!inString && ch === "}") {
        depth--;
        if (depth === 0) {
          try {
            return JSON.parse(trimmed.slice(start, i + 1));
          } catch {
            return null;
          }
        }
      }
    }
  }
  return null;
}

interface Finding {
  severity?: unknown;
  title?: unknown;
  file?: unknown;
  line_start?: unknown;
  body?: unknown;
  recommendation?: unknown;
}

export function formatFindingBody(finding: Finding): string {
  const parts: string[] = [];
  if (typeof finding.title === "string" && finding.title.trim().length > 0) {
    parts.push(finding.title.trim());
  }
  const file = typeof finding.file === "string" ? finding.file.trim() : "";
  const line = Number.isFinite(finding.line_start) ? `:${finding.line_start}` : "";
  const body = typeof finding.body === "string" ? finding.body.trim() : "";
  const fileLine = file ? `${file}${line}` : "";
  if (fileLine && body) parts.push(`${fileLine}: ${body}`);
  else if (fileLine) parts.push(fileLine);
  else if (body) parts.push(body);
  if (typeof finding.recommendation === "string" && finding.recommendation.trim().length > 0) {
    parts.push(finding.recommendation.trim());
  }
  return parts.join("\n");
}

export function parseConcernsJson(message: string): Concerns | null {
  const obj = tryExtractJson(message) as { verdict?: unknown; findings?: unknown } | null;
  if (!obj || typeof obj !== "object") return null;
  if (obj.verdict === "clean") {
    return { high: [], med: [], low: [] };
  }
  if (!Array.isArray(obj.findings)) return null;
  const concerns: Concerns = { high: [], med: [], low: [] };
  for (const f of obj.findings as Finding[]) {
    if (!f || typeof f !== "object") continue;
    const sev = typeof f.severity === "string" ? f.severity.toLowerCase() : "";
    const bucket = SEVERITY_TO_BUCKET[sev];
    if (!bucket) continue;
    const rendered = formatFindingBody(f);
    if (rendered.length === 0) continue;
    concerns[bucket].push(rendered);
  }
  return concerns;
}

export function parseConcernsLegacy(message: string): Concerns {
  const trimmed = message.trim();
  const upper = trimmed.toUpperCase();
  if (upper === "NONE" || upper.startsWith("NONE\n")) {
    return { high: [], med: [], low: [] };
  }
  const parts = trimmed.split(/(?=\[(?:HIGH|MED|LOW)\])/);
  const concerns: Concerns = { high: [], med: [], low: [] };
  for (const part of parts) {
    const labelMatch = part.match(/^\[(HIGH|MED|LOW)\]/);
    if (!labelMatch) continue;
    const body = part.slice(labelMatch[0].length).trim();
    if (body.length === 0) continue;
    const label = labelMatch[1].toLowerCase();
    if (label === "high") concerns.high.push(body);
    else if (label === "med") concerns.med.push(body);
    else if (label === "low") concerns.low.push(body);
  }
  return concerns;
}

export function parseConcerns(message: string): Concerns {
  const fromJson = parseConcernsJson(message);
  if (fromJson) return fromJson;
  return parseConcernsLegacy(message);
}

// Display-only quota reset hint (#176, ADR-120); capture stops at "." so "1.5 hours" yields null (accepted).
const RESET_HINT_PATTERNS = [/try again (?:in|at|after)\s+([^.()\n]+)/i, /\bresets?\s+(?:in|at|after)\s+([^.()\n]+)/i];
const RESET_HINT_MAX_CHARS = 80;

export function parseResetHint(text: unknown): string | null {
  if (typeof text !== "string" || text.length === 0) return null;
  for (const re of RESET_HINT_PATTERNS) {
    const m = text.match(re);
    if (m) {
      const hint = m[1]
        .trim()
        .replace(/[,;].*$/, "")
        .trim();
      // A bare number is a truncated decimal like "1.928s", not a real hint.
      if (/^\d+$/.test(hint)) continue;
      if (hint.length > 0 && hint.length <= RESET_HINT_MAX_CHARS) return hint;
    }
  }
  return null;
}
