// Source of truth: process.mts. The sibling .mjs is generated by `yarn workspace @ask-llm/plugin build:hooks`; never edit it.
// Process-tree termination (ADR-084/088): POSIX signals the process group of a `detached: true` child.
import { spawn } from "node:child_process";
import { platform } from "node:process";
export const IS_WINDOWS = platform === "win32";
export function quoteArgsForWindows(args) {
    return args.map((arg) => {
        if (arg.includes(" ") || arg.includes('"') || arg.includes("&") || arg.includes("|") || arg.includes("^")) {
            return `"${arg.replace(/"/g, '\\"')}"`;
        }
        return arg;
    });
}
export function prepareCommandInvocation(args, options, runtimePlatform = platform) {
    const isWindows = runtimePlatform === "win32";
    return {
        args: isWindows ? quoteArgsForWindows(args) : args,
        options: { ...options, shell: isWindows },
    };
}
export function terminateProcessTree(child, signal) {
    if (!child || typeof child.pid !== "number" || child.killed || child.exitCode !== null) {
        return;
    }
    if (IS_WINDOWS) {
        try {
            spawn("taskkill", ["/pid", String(child.pid), "/f", "/t"], { stdio: "ignore" });
        }
        catch { }
        return;
    }
    try {
        process.kill(-child.pid, signal);
    }
    catch {
        // The group may already be gone; still try the leader.
        try {
            child.kill?.(signal);
        }
        catch { }
    }
}
