// Source of truth: state.mts. The sibling .mjs is generated by `yarn workspace @ask-llm/plugin build:hooks`; never edit it.
// Durable hook state under <markerDir>/.codex-pair/ (ADR-092); atomic-write rules are ADR-086/091.
import { createHash, randomUUID } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, renameSync, statSync, unlinkSync, writeFileSync } from "node:fs";
import { appendFile, mkdir, readdir, readFile, rename, stat, unlink, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
export const PAIR_ROOT_DIR = ".codex-pair";
export const CONTEXT_FILENAME = "context.md";
export const IGNORE_FILENAME = "ignore";
export const LOG_FILENAME = "log.jsonl";
export const MAX_LOG_BYTES = Number(process.env.CODEX_PAIR_MAX_LOG_BYTES ?? 2_000_000);
export const MAX_LOG_ENTRIES = 1000;
export const MAX_LOG_REASON_BYTES = 3500;
export const CACHE_DIR = "cache";
export const CACHE_TTL_MS = 10 * 60 * 1000;
export const CACHE_MAX_ENTRIES = 50;
export const STATE_DIR = "state";
export const PAUSE_SENTINEL_FILE = "paused";
export const INFLIGHT_DIR = "inflight";
export const INFLIGHT_TTL_MIN_MS = 600_000;
// Include-list narrows before the ignore-list excludes (ADR-096).
export const INCLUDE_FILENAME = "include";
export const REPETITIONS_FILENAME = "repetitions.json"; // legacy v1 singleton, unused
// Per-file shards are serialized by the per-file inflight lock (ADR-097).
export const REPETITIONS_SHARDS_DIR = "repetitions";
export const REPETITION_BLOCKING_THRESHOLD = 3;
export const REPETITIONS_SHARD_SCHEMA_VERSION = 2;
export const REPETITIONS_TTL_MS = 30 * 24 * 60 * 60 * 1000;
export const pairRoot = (markerDir) => join(markerDir, PAIR_ROOT_DIR);
export const contextPath = (markerDir) => join(pairRoot(markerDir), CONTEXT_FILENAME);
export const ignorePath = (markerDir) => join(pairRoot(markerDir), IGNORE_FILENAME);
export const logPath = (markerDir) => join(pairRoot(markerDir), LOG_FILENAME);
export const cacheRoot = (markerDir) => join(pairRoot(markerDir), CACHE_DIR);
export const stateRoot = (markerDir) => join(pairRoot(markerDir), STATE_DIR);
export const pausePath = (markerDir) => join(stateRoot(markerDir), PAUSE_SENTINEL_FILE);
export const inflightRoot = (markerDir) => join(stateRoot(markerDir), INFLIGHT_DIR);
// New acks are one shard per hash; readers still merge the legacy singleton.
export const ACKS_FILENAME = "acks.json";
export const ACKS_DIR = "acks";
export const acksPath = (markerDir) => join(stateRoot(markerDir), ACKS_FILENAME);
export const acksRoot = (markerDir) => join(stateRoot(markerDir), ACKS_DIR);
export function ackShardPath(markerDir, hash) {
    const key = createHash("sha256").update(String(hash)).digest("hex");
    return join(acksRoot(markerDir), `${key}.json`);
}
export function readAcks(markerDir) {
    let acks = {};
    try {
        const legacy = JSON.parse(readFileSync(acksPath(markerDir), "utf8"));
        if (legacy && typeof legacy === "object" && !Array.isArray(legacy))
            acks = legacy;
    }
    catch {
        // missing/corrupt legacy state → continue with shards
    }
    let shards = [];
    try {
        shards = readdirSync(acksRoot(markerDir)).filter((name) => name.endsWith(".json"));
    }
    catch {
        // missing shard directory → legacy state (or no acks) is sufficient
    }
    for (const shard of shards) {
        try {
            const { hash, reason, ts } = JSON.parse(readFileSync(join(acksRoot(markerDir), shard), "utf8"));
            if (typeof hash === "string" && typeof reason === "string" && typeof ts === "string") {
                acks[hash] = { reason, ts };
            }
        }
        catch {
            // A corrupt shard must not make unrelated acknowledgements disappear.
        }
    }
    return acks;
}
export function addAck(markerDir, hash, { reason }) {
    const value = { hash, reason, ts: new Date().toISOString() };
    mkdirSync(acksRoot(markerDir), { recursive: true });
    const path = ackShardPath(markerDir, hash);
    const tmp = `${path}.tmp.${process.pid}.${randomUUID()}`;
    writeFileSync(tmp, `${JSON.stringify(value, null, 2)}\n`);
    renameSync(tmp, path);
}
export const includePath = (markerDir) => join(pairRoot(markerDir), INCLUDE_FILENAME);
export const repetitionsPath = (markerDir) => join(stateRoot(markerDir), REPETITIONS_FILENAME);
export const repetitionsShardsRoot = (markerDir) => join(stateRoot(markerDir), REPETITIONS_SHARDS_DIR);
export function repetitionsShardPath(markerDir, file) {
    const hash = createHash("sha256").update(String(file)).digest("hex").slice(0, 16);
    return join(repetitionsShardsRoot(markerDir), `${hash}.json`);
}
export function isPaused(markerDir) {
    try {
        statSync(pausePath(markerDir));
        return true;
    }
    catch {
        return false;
    }
}
// An empty sentinel is a manual pause (manual resume only); a JSON body is a self-healing auto-pause (ADR-120).
export const FAILURES_FILENAME = "failures.json";
export const AUTOPAUSE_FAILURE_THRESHOLD = 3;
export const failuresPath = (markerDir) => join(stateRoot(markerDir), FAILURES_FILENAME);
// Unrecognized bodies read as manual so an unknown pause never auto-expires or gets overwritten.
export function readPauseInfo(markerDir) {
    let raw;
    try {
        raw = readFileSync(pausePath(markerDir), "utf8");
    }
    catch {
        return null;
    }
    const trimmed = raw.trim();
    if (trimmed.length === 0)
        return { manual: true };
    try {
        const parsed = JSON.parse(trimmed);
        if (parsed &&
            typeof parsed === "object" &&
            (parsed.kind === "quota" || parsed.kind === "failures") &&
            typeof parsed.reason === "string") {
            return parsed;
        }
    }
    catch {
        // fall through to manual
    }
    return { manual: true };
}
let _cachedPluginVersion;
export function readPluginVersion() {
    if (_cachedPluginVersion !== undefined)
        return _cachedPluginVersion;
    try {
        const here = dirname(fileURLToPath(import.meta.url));
        const manifest = JSON.parse(readFileSync(join(here, "..", "..", "package.json"), "utf8"));
        _cachedPluginVersion = typeof manifest?.version === "string" ? manifest.version : null;
    }
    catch {
        _cachedPluginVersion = null;
    }
    return _cachedPluginVersion;
}
export const QUOTA_PAUSE_TTL_MS = Number(process.env.CODEX_PAIR_QUOTA_PAUSE_TTL_MS ?? 6 * 3_600_000);
export const FAILURES_PAUSE_TTL_MS = Number(process.env.CODEX_PAIR_FAILURES_PAUSE_TTL_MS ?? 24 * 3_600_000);
// A missing or unparseable `at` counts as expired so a corrupt auto-sentinel cannot kill pairing forever.
export function resolveAutoResume(pauseInfo, { now, currentVersion, quotaTtlMs, failuresTtlMs, } = {}) {
    if (!pauseInfo || pauseInfo.manual)
        return { resume: false };
    const { kind } = pauseInfo;
    if (kind !== "quota" && kind !== "failures")
        return { resume: false };
    if (kind === "failures" &&
        typeof pauseInfo.pluginVersion === "string" &&
        typeof currentVersion === "string" &&
        pauseInfo.pluginVersion !== currentVersion) {
        return { resume: true, why: "plugin-updated" };
    }
    const at = Date.parse(pauseInfo.at);
    const ttl = kind === "quota" ? (quotaTtlMs ?? QUOTA_PAUSE_TTL_MS) : (failuresTtlMs ?? FAILURES_PAUSE_TTL_MS);
    if (!Number.isFinite(at) || (now ?? Date.now()) - at >= ttl) {
        return { resume: true, why: "ttl-expired" };
    }
    return { resume: false };
}
// Never removes a manual pause, and aborts when the sentinel changed since `expected` was read.
export function clearAutoPause(markerDir, expected) {
    const current = readPauseInfo(markerDir);
    if (!current || current.manual)
        return false;
    if (expected && typeof expected === "object" && (current.kind !== expected.kind || current.at !== expected.at)) {
        return false;
    }
    try {
        unlinkSync(pausePath(markerDir));
    }
    catch {
        // already gone
    }
    clearReviewFailures(markerDir);
    return true;
}
// `wx` never overwrites an existing pause, which keeps "notify once" true under concurrency.
export function writeAutoPause(markerDir, { kind, reason, resetHint }) {
    const pluginVersion = readPluginVersion();
    const body = JSON.stringify({
        v: 1,
        kind,
        reason: clampReason(typeof reason === "string" ? reason : String(reason)),
        ...(resetHint ? { resetHint } : {}),
        ...(pluginVersion ? { pluginVersion } : {}),
        at: new Date().toISOString(),
    });
    try {
        mkdirSync(stateRoot(markerDir), { recursive: true });
        writeFileSync(pausePath(markerDir), body, { flag: "wx" });
        return true;
    }
    catch {
        return false;
    }
}
// ponytail: project-global counter is not serialized across files, so a concurrent failure can lose one increment.
export function readFailureCount(markerDir) {
    try {
        const parsed = JSON.parse(readFileSync(failuresPath(markerDir), "utf8"));
        if (parsed && typeof parsed === "object" && typeof parsed.consecutive === "number" && parsed.consecutive > 0) {
            return Math.floor(parsed.consecutive);
        }
    }
    catch {
        // missing/corrupt → 0
    }
    return 0;
}
export function recordReviewFailure(markerDir, reason) {
    const consecutive = readFailureCount(markerDir) + 1;
    const payload = {
        v: 1,
        consecutive,
        lastAt: new Date().toISOString(),
        lastReason: clampReason(typeof reason === "string" ? reason : String(reason)),
    };
    try {
        mkdirSync(stateRoot(markerDir), { recursive: true });
        const p = failuresPath(markerDir);
        const tmp = `${p}.tmp.${process.pid}`;
        writeFileSync(tmp, JSON.stringify(payload));
        renameSync(tmp, p);
    }
    catch {
        // best-effort — counter loss degrades to "pause later", never breaks the hook
    }
    return consecutive;
}
export function clearReviewFailures(markerDir) {
    try {
        unlinkSync(failuresPath(markerDir));
    }
    catch {
        // already clear
    }
}
export function inflightLockPath(markerDir, filePath) {
    const hash = createHash("sha256").update(filePath).digest("hex").slice(0, 16);
    return join(inflightRoot(markerDir), hash);
}
export function tryAcquireInflightLock(markerDir, filePath, ttlMs) {
    const lockPath = inflightLockPath(markerDir, filePath);
    try {
        mkdirSync(dirname(lockPath), { recursive: true });
    }
    catch {
        // mkdir failures fall through — writeFileSync below will report the real error
    }
    try {
        writeFileSync(lockPath, String(process.pid), { flag: "wx" });
        return { acquired: true, lockPath };
    }
    catch (err) {
        if (err?.code !== "EEXIST") {
            return { acquired: false, lockPath, reason: "error" };
        }
    }
    // Identity snapshot + recheck so stale-lock recovery never unlinks a lock refreshed meanwhile (ADR-091).
    let snapshot;
    try {
        const stats = statSync(lockPath);
        if (Date.now() - stats.mtimeMs <= ttlMs) {
            return { acquired: false, lockPath, reason: "in-flight" };
        }
        snapshot = { mtimeMs: stats.mtimeMs, pid: readFileSync(lockPath, "utf8") };
    }
    catch {
        try {
            writeFileSync(lockPath, String(process.pid), { flag: "wx" });
            return { acquired: true, lockPath, recoveredStale: true };
        }
        catch {
            return { acquired: false, lockPath, reason: "race" };
        }
    }
    try {
        const recheck = statSync(lockPath);
        const recheckPid = readFileSync(lockPath, "utf8");
        if (recheck.mtimeMs !== snapshot.mtimeMs || recheckPid !== snapshot.pid) {
            return { acquired: false, lockPath, reason: "in-flight" };
        }
    }
    catch {
        // Vanished between snapshot and recheck — fall through to retry create
    }
    try {
        unlinkSync(lockPath);
    }
    catch {
        // someone else already cleaned up — fine, fall through to retry
    }
    try {
        writeFileSync(lockPath, String(process.pid), { flag: "wx" });
        return { acquired: true, lockPath, recoveredStale: true };
    }
    catch {
        return { acquired: false, lockPath, reason: "race" };
    }
}
export function releaseInflightLock(lockPath) {
    if (!lockPath)
        return;
    try {
        unlinkSync(lockPath);
    }
    catch {
        // already gone — fine
    }
}
export function computeCacheKey({ model, prompt, fileContent, surfaceThreshold, }) {
    const h = createHash("sha256");
    h.update(model);
    h.update("\0");
    h.update(prompt);
    h.update("\0");
    h.update(fileContent);
    h.update("\0");
    h.update(surfaceThreshold);
    return h.digest("hex");
}
export function cachePathFor(markerDir, cacheKey) {
    return join(cacheRoot(markerDir), cacheKey.slice(0, 2), `${cacheKey.slice(2)}.json`);
}
export async function getCachedConcerns(markerDir, cacheKey) {
    const cachePath = cachePathFor(markerDir, cacheKey);
    try {
        const stats = await stat(cachePath);
        if (Date.now() - stats.mtimeMs > CACHE_TTL_MS)
            return null;
        const raw = await readFile(cachePath, "utf8");
        const parsed = JSON.parse(raw);
        if (!parsed || !Array.isArray(parsed.high) || !Array.isArray(parsed.med) || !Array.isArray(parsed.low)) {
            return null;
        }
        return parsed;
    }
    catch {
        return null;
    }
}
export async function setCachedConcerns(markerDir, cacheKey, value) {
    const cachePath = cachePathFor(markerDir, cacheKey);
    try {
        await mkdir(dirname(cachePath), { recursive: true });
        const tmpPath = `${cachePath}.tmp.${process.pid}`;
        await writeFile(tmpPath, JSON.stringify(value));
        await rename(tmpPath, cachePath);
    }
    catch {
        // intentional no-op — cache write failures must never break Claude's flow
    }
    await evictCacheOldest(markerDir);
}
export async function evictCacheOldest(markerDir) {
    try {
        const root = cacheRoot(markerDir);
        const entries = [];
        const prefixes = await readdir(root);
        for (const prefix of prefixes) {
            let files;
            try {
                files = await readdir(join(root, prefix));
            }
            catch {
                continue;
            }
            for (const file of files) {
                const full = join(root, prefix, file);
                try {
                    const s = await stat(full);
                    entries.push({ path: full, mtimeMs: s.mtimeMs });
                }
                catch {
                    // skip unreadable entries
                }
            }
        }
        if (entries.length <= CACHE_MAX_ENTRIES)
            return;
        entries.sort((a, b) => a.mtimeMs - b.mtimeMs);
        const drop = entries.slice(0, entries.length - CACHE_MAX_ENTRIES);
        for (const e of drop) {
            try {
                await unlink(e.path);
            }
            catch {
                // skip if already deleted by a concurrent run
            }
        }
    }
    catch {
        // intentional no-op — eviction is best-effort
    }
}
export async function rotateLogIfNeeded(targetLogPath) {
    try {
        const stats = await stat(targetLogPath);
        if (stats.size <= MAX_LOG_BYTES)
            return;
        const content = await readFile(targetLogPath, "utf8");
        const lines = content.split("\n").filter((l) => l.length > 0);
        if (lines.length <= MAX_LOG_ENTRIES)
            return;
        const tail = lines.slice(-MAX_LOG_ENTRIES);
        // PID-scoped tmp keeps concurrent rotations from tearing each other (ADR-091).
        const tmpPath = `${targetLogPath}.tmp.${process.pid}`;
        await writeFile(tmpPath, `${tail.join("\n")}\n`);
        await rename(tmpPath, targetLogPath);
    }
    catch {
        // intentional no-op — rotation is best-effort
    }
}
export function clampReason(reason) {
    if (typeof reason !== "string")
        return reason;
    // PIPE_BUF atomicity is in bytes; back off continuation bytes so the cut never splits a codepoint.
    const byteLen = Buffer.byteLength(reason, "utf8");
    if (byteLen <= MAX_LOG_REASON_BYTES)
        return reason;
    const buf = Buffer.from(reason, "utf8");
    let end = MAX_LOG_REASON_BYTES;
    while (end > 0 && (buf[end] & 0xc0) === 0x80)
        end--;
    const dropped = byteLen - end;
    return `${buf.subarray(0, end).toString("utf8")}…(${dropped}b truncated)`;
}
export async function appendLog(markerDir, entry) {
    const target = logPath(markerDir);
    try {
        await mkdir(dirname(target), { recursive: true });
    }
    catch {
        // ignore — appendFile will surface the real failure
    }
    const safe = entry?.reason !== undefined ? { ...entry, reason: clampReason(entry.reason) } : entry;
    try {
        await appendFile(target, `${JSON.stringify(safe)}\n`);
    }
    catch {
        // logging failures must never break Claude's flow
        return;
    }
    await rotateLogIfNeeded(target);
}
export function hashConcernBody(body) {
    return createHash("sha256").update(String(body)).digest("hex").slice(0, 16);
}
export function loadRepetitionsForFile(markerDir, file) {
    const p = repetitionsShardPath(markerDir, file);
    try {
        const raw = readFileSync(p, "utf-8");
        const parsed = JSON.parse(raw);
        if (!parsed || typeof parsed !== "object")
            return new Map();
        if (parsed.v !== REPETITIONS_SHARD_SCHEMA_VERSION)
            return new Map();
        if (!Array.isArray(parsed.entries))
            return new Map();
        const map = new Map();
        for (const e of parsed.entries) {
            if (!e || typeof e !== "object")
                continue;
            if (typeof e.hash !== "string")
                continue;
            if (typeof e.count !== "number" || e.count <= 0)
                continue;
            map.set(e.hash, {
                hash: e.hash,
                count: e.count,
                firstSeenAt: e.firstSeenAt ?? new Date().toISOString(),
                lastSeenAt: e.lastSeenAt ?? new Date().toISOString(),
            });
        }
        return map;
    }
    catch {
        return new Map();
    }
}
export async function saveRepetitionsForFile(markerDir, file, map) {
    const p = repetitionsShardPath(markerDir, file);
    const payload = {
        v: REPETITIONS_SHARD_SCHEMA_VERSION,
        file,
        entries: Array.from(map.values()),
    };
    try {
        await mkdir(dirname(p), { recursive: true });
        const tmp = `${p}.tmp.${process.pid}`;
        await writeFile(tmp, JSON.stringify(payload));
        await rename(tmp, p);
    }
    catch {
        // best-effort — repetitions are advisory; failure must not break hook
    }
}
// Read-only so cache hits never increment counts.
export function getBlockingFromShard(markerDir, file, newHashes) {
    const map = loadRepetitionsForFile(markerDir, file);
    const blocking = [];
    for (const h of newHashes) {
        const e = map.get(h);
        if (e && e.count >= REPETITION_BLOCKING_THRESHOLD) {
            blocking.push({ file, hash: e.hash, count: e.count });
        }
    }
    return blocking;
}
// Live reviews only: hashes absent from this review are assumed fixed and dropped.
export async function updateRepetitions(markerDir, file, newHashes) {
    const map = loadRepetitionsForFile(markerDir, file);
    const newSet = new Set(newHashes);
    const now = new Date().toISOString();
    for (const [hash, entry] of [...map.entries()]) {
        if (newSet.has(hash)) {
            entry.count += 1;
            entry.lastSeenAt = now;
            newSet.delete(hash);
        }
        else {
            map.delete(hash);
        }
    }
    for (const hash of newSet) {
        map.set(hash, { hash, count: 1, firstSeenAt: now, lastSeenAt: now });
    }
    await saveRepetitionsForFile(markerDir, file, map);
    if (Math.random() < 0.05) {
        sweepStaleRepetitions(markerDir).catch(() => { });
    }
    const blocking = [];
    for (const entry of map.values()) {
        if (entry.count >= REPETITION_BLOCKING_THRESHOLD) {
            blocking.push({ file, hash: entry.hash, count: entry.count });
        }
    }
    return blocking;
}
export async function sweepStaleRepetitions(markerDir) {
    const root = repetitionsShardsRoot(markerDir);
    try {
        const files = await readdir(root);
        const cutoff = Date.now() - REPETITIONS_TTL_MS;
        for (const f of files) {
            if (!f.endsWith(".json"))
                continue;
            const full = join(root, f);
            try {
                const s = await stat(full);
                if (s.mtimeMs < cutoff)
                    await unlink(full);
            }
            catch {
                // skip unreadable / racing-unlink
            }
        }
    }
    catch {
        // shards dir doesn't exist yet — nothing to sweep
    }
}
// Dead v1 singleton API (ADR-097), kept for existing callers.
export function loadRepetitions(markerDir) {
    void markerDir;
    return new Map();
}
export async function saveRepetitions(markerDir, map) {
    void markerDir;
    void map;
}
