// Source of truth: stop-gate.mts. The sibling .mjs is generated by `yarn workspace @ask-llm/plugin build:hooks`; never edit it.
// Pure, I/O-free gate logic for the codex-pair Stop hook (#142, ADR-118).
import { isAbsolute, join, relative } from "node:path";
import { hashConcernBody } from "./state.mjs";
// In -z mode git does not quote paths, and a rename's destination record is followed by its source record.
export function parseGitPorcelain(stdout, repoRoot) {
    const dirty = new Set();
    const records = stdout.split("\0");
    for (let i = 0; i < records.length; i++) {
        const record = records[i];
        if (record.length < 4)
            continue;
        const status = record.slice(0, 2);
        const path = record.slice(3);
        dirty.add(isAbsolute(path) ? path : join(repoRoot, path));
        if (status.includes("R") || status.includes("C"))
            i++;
    }
    return dirty;
}
// Verdicts without a trustworthy final-state review; `retried`/`broker_fallback` carry no `file` today.
const INDETERMINATE = new Set(["skipped", "error", "retried", "broker_fallback"]);
export function collectBlockingHighs({ entries, acks, existsFn, gitDirty, markerDir, }) {
    const blocking = [];
    for (const [file, entry] of entries) {
        if (!existsFn(file))
            continue; // [A] deleted/renamed
        if (INDETERMINATE.has(entry.verdict))
            continue; // [C] indeterminate latest → fail-open
        if (gitDirty && !gitDirty.has(file))
            continue; // [B] clean vs HEAD
        const highs = Array.isArray(entry.concerns?.high) ? entry.concerns.high : [];
        for (const text of highs) {
            const hash = hashConcernBody(`${relative(markerDir, file)}:${text}`); // [E] file-scoped
            if (!acks[hash])
                blocking.push({ file, text, hash });
        }
    }
    return blocking;
}
export function formatBlockMessage(blocking, markerDir) {
    const lines = blocking.map((b) => {
        const rel = relative(markerDir, b.file);
        return `  [${b.hash}] ${rel}\n    ${b.text}`;
    });
    return (`🚫 codex-pair: ${blocking.length} unaddressed HIGH finding(s) (blockOn: HIGH). ` +
        `Fix them, or defer each with /codex-pair-ack.\n\n` +
        `${lines.join("\n")}\n\n` +
        `To defer a finding (stale / pre-existing / out-of-scope), run /codex-pair-ack with its [hash] from the list above — e.g.:\n` +
        `  /codex-pair-ack ${blocking[0].hash} "<reason>"\n` +
        `(If you fixed a finding by editing a DIFFERENT file, make a real edit to the ` +
        `flagged file so it gets re-reviewed — an identical re-touch hits the review cache.)`);
}
// A settling debounce record or a fresh inflight lock means a verdict would land after the turn ends.
export function collectInFlight({ records, lockMtimes, now, freshMs, staleMs = 600_000, }) {
    const settling = [];
    for (const r of records) {
        if (!r || typeof r !== "object" || typeof r.file !== "string")
            continue;
        if (!(typeof r.generation === "number" && typeof r.reviewedGen === "number"))
            continue;
        if (r.reviewedGen >= r.generation)
            continue;
        if (Number.isFinite(r.burstStartedAt) && now - r.burstStartedAt > staleMs)
            continue;
        settling.push(r.file);
    }
    const reviewing = lockMtimes.filter((m) => Number.isFinite(m) && now - m < freshMs).length;
    return { settling, reviewing, any: settling.length > 0 || reviewing > 0 };
}
const MAX_SETTLING_LISTED = 5;
export function formatInFlightMessage({ settling, reviewing }, markerDir) {
    const parts = [];
    if (settling.length > 0) {
        const listed = settling.slice(0, MAX_SETTLING_LISTED).map((f) => relative(markerDir, f));
        const extra = settling.length > MAX_SETTLING_LISTED ? ` (+${settling.length - MAX_SETTLING_LISTED} more)` : "";
        parts.push(`${settling.length} edited file(s) awaiting review: ${listed.join(", ")}${extra}`);
    }
    if (reviewing > 0)
        parts.push(`${reviewing} review(s) running`);
    return (`⏳ codex-pair: review(s) still in flight — ${parts.join("; ")}. ` +
        `Verdicts land in ${join(markerDir, ".codex-pair", "log.jsonl")}. ` +
        `Wait for them (e.g. \`sleep 45\`), read the newest entries for the files you edited, ` +
        `address any HIGH findings, then end the turn.`);
}
// The log is append-only, so the last entry per file is its latest review.
export function selectLatestEntries(logText) {
    const latest = new Map();
    for (const line of logText.split("\n")) {
        const t = line.trim();
        if (!t)
            continue;
        let entry;
        try {
            entry = JSON.parse(t);
        }
        catch {
            continue;
        }
        if (entry && typeof entry.file === "string")
            latest.set(entry.file, entry);
    }
    return latest;
}
